### ISSUE TITLE
本地存放图片的路径能不能用变量

### ISSUE THREAD

**Issue by alexzhengzzz** [imlinhanchao/vsc-markdown-image#10]
./${filename}/ 类似于typora
![image](https://user-images.githubusercontent.com/18068039/90085605-f2db5400-dd4a-11ea-9102-cb4b823b3eff.png)

**Comment by imlinhanchao** [comment]
你可以在 `markdown-image.base.fileNameFormat` 设置 `${filename}/your_file_name_role`；然后在 `markdown-image.coding.path` 设置 `./` 。

**Comment by alexzhengzzz** [comment]
谢谢
