### ISSUE TITLE
大佬，阿里云对象存储如何配置

### ISSUE THREAD

**Issue by qqlcx5** [imlinhanchao/vsc-markdown-image#101]
不会自己diy，求来一个不配自己配置的

**Comment by imlinhanchao** [comment]
![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/1502581/50cc8923-9d5c-4649-916d-5e490e32c4f5)
这些就是你需要配置的，我没有使用过 阿里云的对象存储，不确定具体这些设置项目在什么位置。
你可以参考这个阿里云对象存储的文档：https://help.aliyun.com/document_detail/451966.html
或是问问客服。
