### ISSUE TITLE
新发布版本的文件名格式化出现问题

### ISSUE THREAD

**Issue by coldestlin** [imlinhanchao/vsc-markdown-image#103]
我这边配置的图片文件名格式是

Base: File Name Format:

```
${YY}-${MM}/${YY}${MM}${DD}${hh}${mm}${ss}-${rand,100000}
```

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/19356579/1edbc7ff-f294-4287-903a-629744a69839)

最近第二个YY/MM无法被解析,  粘贴的文件名被解析为

```
![picture 5](/assets/2023-06/${YY}${MM}30110819-43833.png)  
```

估计最近的更新引入了一个bug, 同一个参数只解析一遍.

看了下插件的更新记录, 刚好是前两天28号更新的.  

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/19356579/7a738b42-417e-497d-ba4c-d0f7faead196)

**Comment by imlinhanchao** [comment]
这部分确实有更新，我复现修正一下

**Comment by imlinhanchao** [comment]
问题已修正，更新到 1.3.35 可以解决。
