### ISSUE TITLE
阿里云s3上传报错

### ISSUE THREAD

**Issue by qqlcx5** [imlinhanchao/vsc-markdown-image#106]
![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/31888710/f37636a0-2919-45a1-ab34-1b8d6142bfd5)
报错，
new NodeError (node:internal/errors:387:5) at URL.onParseError (node:internal/url:564:9) at new URL (node:internal/url:640:5) at parseUrl (c:\Users\ccuser\.vscode\extensions\hancel.markdown-image-1.1.35\node_modules\@aws-sdk\url-parser\dist-cjs\index.js:7:38) at toEndpointV1 (c:\Users\ccuser\.vscode\extensions\hancel.markdown-image-1.1.35\node_modules\@aws-sdk\middleware-endpoint\dist-cjs\adaptors\toEndpointV1.js:12:38) at customEndpointProvider (c:\Users\ccuser\.vscode\extensions\hancel.markdown-image-1.1.35\node_modules\@aws-sdk\middleware-endpoint\dist-cjs\resolveEndpointConfig.js:10:99) at processTicksAndRejections (node:internal/process/task_queues:96:5)

其他相似s3插件使用没有任何问题。应该账号配置问题
![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/31888710/44039e58-491c-47a3-8333-d769d37a6144)

**Comment by imlinhanchao** [comment]
s3 支援是由 @zzeebbii 提供的 PR( #94 )，我没有使用过任何 s3 产品，只能看看 PR 原作者能否修复了（或是你懂 Typescript 的话，也可以帮忙修正）。请帮忙更新 Issue ，增加英文描述说明你遇到的问题。谢谢！

Hi~@zzeebbii . Can you help me to check this issue? Thanks.

**Comment by zzeebbii** [comment]
It seems that the `Endpoint` and `Region` values are same but in practice, these two values are different. Combining these two values provide the URL to the bucket and since the values are not right, the error is thrown. I'd suggest the reporter make sure that the `Region` value is right. I haven't used Alibaba Cloud but I'll check their documentation.

**Comment by zzeebbii** [comment]
Quickly checking the documentation link here:
https://www.alibabacloud.com/help/en/oss/user-guide/regions-and-endpoints?spm=a2c63.p38356.0.0.1d635c4cPBuKPG

It seems that the `Region` value should be `oss-cn-hongkong`. Maybe the reporter can try this value and give it a try.

**Comment by qqlcx5** [comment]
蟹蟹，我试十多种写法，最后可以使用了。
Crab crab, I tried more than ten ways to write it, and finally I can use it.
![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/31888710/5c89a588-f22b-4ba4-b26d-520f85891156)
给你们添麻烦了
So much trouble for you
参考s3各个云存储相关的参数
For details, see s3 cloud storage related parameters
https://doc-zh.zego.im/faq/vendor_params?product=CloudRecording&platform=all
https://help.aliyun.com/zh/oss/user-guide/regions-and-endpoints
