### ISSUE TITLE
Markdown代码的占位符是否可以增加上传的文件名变量？

### ISSUE THREAD

**Issue by sumumo** [imlinhanchao/vsc-markdown-image#107]
Markdown代码的占位符是否可以增加上传的文件名变量？

**Comment by imlinhanchao** [comment]
有，就是 `filename`

**Comment by sumumo** [comment]
> 有，就是 `filename`

不好意思，是我没表达清楚，不是图片原始的文件名，是设置的那个上传的文件名，File Name Format

**Comment by imlinhanchao** [comment]
你 File Name Format 设置是什么？

**Comment by sumumo** [comment]
> 你 File Name Format 设置是什么？

${YY}/${prompt}

**Comment by imlinhanchao** [comment]
这是个 bug，稍后修正。

**Comment by imlinhanchao** [comment]
> > 你 File Name Format 设置是什么？
> 
> ${YY}/${prompt}

问题已修正，使用 `filename` 变量即可。需更新到 1.1.36 。

**Comment by sumumo** [comment]
> > > 你 File Name Format 设置是什么？
> > 
> > 
> > ${YY}/${prompt}
> 
> 问题已修正，使用 `filename` 变量即可。需更新到 1.1.36 。

感谢♪(･ω･)ﾉ
