### ISSUE TITLE
local.path not working

### ISSUE THREAD

**Issue by xianshenglu** [imlinhanchao/vsc-markdown-image#108]
Hi, I'm trying to paste the image and save to `../images/${YY}${MM}${DD}${hh}${mm}${ss}`, but not working. 

I have tried many times.

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/23273077/c7d7e841-138b-4dac-9364-597cd73a1885)

or 

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/23273077/72e8bf3b-6ab7-47a8-88c9-b1b144c95bbc)

The image will always be saved to `![Alt text](image-1.png)`

Any ideas?

**Comment by xianshenglu** [comment]
I found it's controlled by vscode default markdown extension.

**Comment by xianshenglu** [comment]
So, I end up with 

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/23273077/87d886d3-d308-49a7-a16f-1951ffc4505b)

**Comment by imlinhanchao** [comment]
如果你用 `Ctrl + Shift + V` 或右键菜单的 `粘贴图片` 应该会是正确的。
