### ISSUE TITLE
插件突然不能使用了？

### ISSUE THREAD

**Issue by liqiwenx** [imlinhanchao/vsc-markdown-image#109]
VScode info
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

插件为什么突然不能使用了？ [shift+alt+v]没有反应了. 是跟vscode自带的markdown编辑器粘贴功能有冲突吗?

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/52438879/3114d362-7e41-49e4-868e-549b6c4c091a)

**Comment by imlinhanchao** [comment]
使用右键粘贴图片是否可以？

**Comment by liqiwenx** [comment]
> 使用右键“粘贴图片”菜单是否可以？

我使用的时sftp方式, 将图片粘贴到服务器上的文档中.  [shift+alt+v]和鼠标右键点击[Paste Image] 都没有反应

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/52438879/d92cf0ca-40b7-4177-ab88-3c4736e1e3aa)

**Comment by imlinhanchao** [comment]
你是remote mode？

**Comment by liqiwenx** [comment]
> 你是remote mode？

对的，remote mode。使用sftp把图片粘贴到远程文件里

**Comment by imlinhanchao** [comment]
本地模式是否正常？

**Comment by liqiwenx** [comment]
> 本地模式是否正常？

刚试了以下, 本地模式是正常的.  应该是就remote mode + sftp的方式, 没有反应

**Comment by imlinhanchao** [comment]
我确认一下

**Comment by imlinhanchao** [comment]
我测试了一下可以正常上传，你有提示什么错误吗？FileNameFormat 设置成了什么？

**Comment by liqiwenx** [comment]
> 我测试了一下可以正常上传，你有提示什么错误吗？FileNameFormat 设置成了什么？

现象是快捷键和右键菜单都没有反应，没有任何提示。如果你的环境下验证是正常的话，那我后面再重新配置一遍环境再试一下吧。

`${mdname}.assets/${YY}${MM}${DD}${HH}${mm}${ss}`

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/52438879/c008c7b8-453a-41b1-bf74-fa037490e111)

**Comment by imlinhanchao** [comment]
你可以下载一个 sftp 测试一下服务器是 sftp 是否可以正常使用。

**Comment by liqiwenx** [comment]
> 你可以下载一个 sftp 测试一下服务器是 sftp 是否可以正常使用。

好的，感谢帮助

**Comment by liqiwenx** [comment]
补充：当我按下[shift+alt+v]时，日志窗口中有如下log，供参考：

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/52438879/e77a791b-eedf-4bc2-8cde-66c42f3631eb)

**Comment by imlinhanchao** [comment]
这是解析你剪切板没有找到任何图片。你是什么系统？

**Comment by liqiwenx** [comment]
> 这是解析你剪切板没有找到任何图片。你是什么系统？

我本地是Windows，VScode通过ssh连接到远程Linux上

Windows：
设备名称	qiwenli
设备全名	qiwenli.nextvpu.local
处理器	AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz
机带 RAM	16.0 GB (15.4 GB 可用)
设备 ID	E1254CFD-0657-4666-8ACF-5C6468A7F885
产品 ID	00331-10000-00001-AA336
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入


Linux Server：

Linux nextvpu-15 4.15.0-197-generic #208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by imlinhanchao** [comment]
那应该没问题呀，本地 Windows 会调用 Powershell 解析
