### ISSUE TITLE
Support custom image url for local files

### ISSUE THREAD

**Issue by iootaa** [imlinhanchao/vsc-markdown-image#11]
Hi there, and thanks for this extension

it's already possible to setup a custom folder where the file is save locally. But this folder is often different than the URL we want to insert in the markdown file. It would be great to make it possible to customize the latter.

To understand better, please refer to `pasteImage.path` and `pasteImage.basePath` in the extension "[PasteImage](https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image)" (which only supports pasting from clipboard)

Thank you, cheers

**Comment by imlinhanchao** [comment]
You can save this code as a javascript file.
```javascript
const path = require('path');
const fs = require('fs');

module.exports = async function(filePath, savePath, markdownPath) {
    // Return a picture access link
    fs.copyFileSync(filePath, savePath);
    return 'your_url_prefix' + path.basename(filePath); 
}
```
And then set the `markdown-image.base.uploadMethod` to **DIY**. Set `markdown-image.DIY.path`  to the javascript file path.

**Comment by imlinhanchao** [comment]
Is that resolve your problem? I will close this issue. If you has many feedback. You can reply this issue.
