### ISSUE TITLE
使用SFTP上传的时候没有配置成功

### ISSUE THREAD

**Issue by dyc87112** [imlinhanchao/vsc-markdown-image#110]
您好，感谢作者提供这么好的插件。

之前一直在用local模式，最近看到有支持sftp，所以打算整一下，但是没成功。

看文档说要加"remote.extensionKind"，不确定是否是在`setting.json`里加？

我目前是这样子配置的：

```json
{
    "remote.extensionKind": {
        "hancel.markdown-image": [
          "ui"
        ]
    },
    "markdown-image.sftp.host":"1.1.1.1",
    "markdown-image.sftp.port": 22,
    "markdown-image.sftp.username": "aaa",
    "markdown-image.sftp.password": "bbb",
    "markdown-image.sftp.privateKeyPath": "/etc/ssh/",
    "markdown-image.sftp.referencePath": "https://xxx.com/images/${mdname}", 
    "markdown-image.sftp.path": "/"
}
```

确认了SFTP服务器是没问题的，本地通过SFTP客户端是可以连接的。

同时，看VSCode输出窗口也没有报错信息。不知道是哪里配置不对，望指导 🙏

**Comment by imlinhanchao** [comment]
这个功能是给 Remote Mode  的用户使用的。对于 Remote Mode 的用户是无法使用 Local 方式保存文件的，因此通过 Sftp 来替代 Local 上传。Remote mode 需要安装 Remote SSH 插件来连接打开远程服务器的目录，进而使用此插件上传。

**Comment by dyc87112** [comment]
好的，感谢解答
