### ISSUE TITLE
[功能请求] 支持将base64字符转为图片进行上传，支持vscode web(https://vscode.dev)浏览器编辑器 

### ISSUE THREAD

**Issue by xqdd** [imlinhanchao/vsc-markdown-image#112]
1. 目前无法在浏览器版本的vscode中使用，~~在浏览器中不好读取剪切板中的图片的话~~，浏览器的剪切板api可以读取到图片，测试了安卓也可以。[安卓复制图片到剪切板](https://www.reddit.com/r/Android/comments/lxkc0v/did_you_know_you_can_copy_and_paste_images_in/)
2. 希望支持base64转图片再上传到图床，至于base64图片如何来，chrome有截图插件，应该可以截完图选择复制为base64字符，这样在浏览器中也能进行截图上传了（并且变相支持了ipad、安卓平板，有些手机浏览器是支持安装扩展的，平板生产力MAX）

![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/20871761/be57af52-aa55-4696-8f67-d51fc9867287)

https://code.visualstudio.com/docs/editor/vscode-web#_extensions

**Comment by xqdd** [comment]
PS：不直接粘base64字符图片到markdown的原因是文本太长了，导致markdown原生格式的可读性和可编辑性变得特别差

**Comment by imlinhanchao** [comment]
Web vscode 插件环境与浏览器还是有差异的，其本质依然是在vscode提供的沙盒中运行，并无法如同Web那般直接调用剪贴板。

**Comment by xqdd** [comment]
看到这里有提到这个权限，不知道是不是支持

https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-a-browser-using-vscodetestweb

![Screenshot_2023-09-23-08-48-36-789_com microsoft emmx](https://github.com/imlinhanchao/vsc-markdown-image/assets/20871761/76caae61-da3b-48c4-ba04-3384a3f091e3)

**Comment by imlinhanchao** [comment]
这只是Web扩展的测试说明

**Comment by xqdd** [comment]
是支持的，但是这能读取文本。。还不能读取图片，记录在vscode的开发债务里面。。估计这个特性支持遥遥无期

https://code.visualstudio.com/api/references/vscode-api#Clipboard

https://github.com/microsoft/vscode/issues/141704

**Comment by imlinhanchao** [comment]
从目前结果看，vscode 官方无计划支援此功能。
