### ISSUE TITLE
【功能请求】插入图片自动居中（或靠右、靠左）

### ISSUE THREAD

**Issue by AtomSatellite** [imlinhanchao/vsc-markdown-image#115]
希望作者可以加入设置图片位置的功能😁

**Comment by imlinhanchao** [comment]
Markdown 标准语法是没有图片对齐方式设置的。这个功能应该不会添加。

**Comment by AtomSatellite** [comment]
> Markdown 标准语法是没有图片对齐方式设置的。这个功能应该不会添加。

thanks，不过用html语法的话好像也可以
