### ISSUE TITLE
Support for Azure Blob storage

### ISSUE THREAD

**Issue by V4A001** [imlinhanchao/vsc-markdown-image#118]
Does your solution support Azure Blob Storage?

**Comment by imlinhanchao** [comment]
I have not used Azure Blob Storage.  It appears to be the s3 protocol?  You can try using s3 configuration.

**Comment by V4A001** [comment]
S3 does not work. Blob storage has a connection string. I will contribute 25 USD if you can add blob storage. If you can make that 2 different blob storages can be used in 1 visual studio project I will donate 25 USD more. I am working on documentation on 2 different repositories and the images should go to 2 different storage accounts/ blobs.

**Comment by imlinhanchao** [comment]
Thanks.  I will try it.  But now it’s Spring Festival in my country.  I'm on vacation.  Probably not going to try it anytime soon.

**Comment by imlinhanchao** [comment]
Thanks.  I will try it.  But now it’s Spring Festival in my country.  I'm on vacation.  Probably not going to try it anytime soon.

**Comment by V4A001** [comment]
Enjoy! Have had software company 25 years ago in Hangzhou and Beijing.

**Comment by imlinhanchao** [comment]
It's support Azure Blob Storage now. Please update to version 1.1.37 to use it. 

Regarding your second request: to upload to two different repositories simultaneously, the current overall architecture cannot be configured to allow uploads to two different repositories. 

However, you can achieve parallel uploads using the DIY mode. Save the following code as a file, set the file path in `markdown-image.DIY.path`, and add DIY as an upload method in `markdown-image.base.uploadMethods`. This will enable simultaneous uploads to two different repositories.

```javascript
const { BlobServiceClient } = require("@azure/storage-blob");

const config = {
  connectionString: "other connect string",
  container: "other container"
};

module.exports = async function (filePath, savePath, markdownPath) {
  const blobServiceClient = BlobServiceClient.fromConnectionString(
    config.connectionString
  );

  const containerClient = blobServiceClient.getContainerClient(config.container);
  const blockBlobClient = containerClient.getBlockBlobClient(savePath);
  await blockBlobClient.uploadFile(filePath);

  return blockBlobClient.url;
}
```

**Comment by V4A001** [comment]
Thank you. I am trying to use, but get this error:
````typescript

Upload File Failed: Unable to extract accountName with provided information.

I only need to add https://<my storage accountname>.blob.core.windows.net

and my blob name <blobname>

And turn Entra ID identification on?

**Comment by V4A001** [comment]
> Regarding your second request: to upload to two different repositories simultaneously, the current overall architecture cannot be configured to allow uploads to two different repositories.

I have multiple repositories I am working on from 1 work space. So I have different repositories for docs, docs-technical, docs-internal. The docs are for customers, the docs-technical for the technical persons and the docs-internal for internal use. The repositories do not have images. Those are uploaded to the respective repositories so also access on the images is limited per user group.

I can open of course a Visual Studio for every repository but not sure if that would work. It is much comfortable to have all together to work on:
![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/9630343/23a5c02c-bef8-4484-80a5-6de37dd324b0)

**Comment by V4A001** [comment]
I do not see this in your code:
https://learn.microsoft.com/en-us/azure/developer/javascript/sdk/authentication/local-development-environment-developer-account

**Comment by imlinhanchao** [comment]
> Thank you. I am trying to use, but get this error:
> 
> ```ts
> Upload File Failed: Unable to extract accountName with provided information.
> ```
> 
> I only need to add https://.blob.core.windows.net
> 
> and my blob name
> 
> And turn Entra ID identification on?

Is the connect string from here:
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-nodejs?tabs=connection-string%2Croles-azure-portal%2Csign-in-azure-cli#authenticate-to-azure-and-authorize-access-to-blob-data

**Comment by imlinhanchao** [comment]
> > Regarding your second request: to upload to two different repositories simultaneously, the current overall architecture cannot be configured to allow uploads to two different repositories.
> 
> I have multiple repositories I am working on from 1 work space. So I have different repositories for docs, docs-technical, docs-internal. The docs are for customers, the docs-technical for the technical persons and the docs-internal for internal use. The repositories do not have images. Those are uploaded to the respective repositories so also access on the images is limited per user group.
> 
> I can open of course a Visual Studio for every repository but not sure if that would work. It is much comfortable to have all together to work on: ![image](https://private-user-images.githubusercontent.com/9630343/305725767-23a5c02c-bef8-4484-80a5-6de37dd324b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyOTk3MjQsIm5iZiI6MTcwODI5OTQyNCwicGF0aCI6Ii85NjMwMzQzLzMwNTcyNTc2Ny0yM2E1YzAyYy1iZWY4LTQ0ODQtODBhNS02ZGUzN2RkMzI0YjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMjMzNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY3YjIwOTVjZWYwY2IzMzk0MTI5NWYwNzRjNGExZWI2MmEwYjcwMjhhYjEzNTVlYzZjNWRmZDlmMWUxYjZiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IYZx8lEDoxVPaZupNbhZPI_sR239_ij9ksy7vfqm8Fg)

Oh, I misunderstood your requirement. I thought you wanted to upload to two different blobs simultaneously. In reality, you want to upload MD files from different folders to different blobs.

To achieve this, you can indeed configure it by having different settings.json files within different .vscode directories. If you prefer to have only one instance of vscode open, you can create a new workspace and add different folders to it. Then, within each folder, use a different settings.json file for configuration.

**Comment by V4A001** [comment]
Thank you for the quick reply. Happy New Year, I forgot.

I will try with different directories. Is it difficult to change/ add the Entra Id access on personal user flow instead of a shared key? The key is shared between users which I do not like. Their own account with MFA would be better.

**Comment by V4A001** [comment]
With access key works by the way! I will look into the .vscode setup later.

**Comment by V4A001** [comment]
Payment done.

**Comment by imlinhanchao** [comment]
It‘s support Passwordless authentication method now. You can have a try.

**Comment by V4A001** [comment]
I have rotated the access key. Disabled the usage and allowed anonymous read access. Works as a charm! You are the BEST! Thank you.
