### ISSUE TITLE
图片文件名上自动生成时间比实际计算机时间快了 16 小时

### ISSUE THREAD

**Issue by QuentinHsu** [imlinhanchao/vsc-markdown-image#12]
如图所示，贴图文件名的自动生成时间比当前计算机时间快了 16 小时。

![image](https://user-images.githubusercontent.com/21162238/96412885-5dae7d00-121d-11eb-85da-f5c471a21894.png)

虽说这个一般不太会被关注，但可能会影响以后的信息查找。

望排查修复下该问题！感谢！

**Comment by imlinhanchao** [comment]
問題已修復，請更新到 1.0.9 。謝謝反饋！

**Comment by imlinhanchao** [comment]
看起來應該沒有什麽問題了吧？有問題請再回復 Issue 。
