### ISSUE TITLE
请求对S3上传文件自动判断Content-Type

### ISSUE THREAD

**Issue by hzj629206** [imlinhanchao/vsc-markdown-image#123]
目前上传的图片都是 `Content-Type: application/octet-stream`. 可以在上传时判断并指定Content-Type.

如下示例：

```
// https://github.com/imlinhanchao/vsc-markdown-image/blob/master/src/lib/s3.ts#L78

require ("mime")

new PutObjectCommand({
          Bucket: bucketName,
          Key: storageKey,
          Body: storageFilesMap[storageKey],
          ContentType: mime.getType(storageKey),
})
```

**Comment by imlinhanchao** [comment]
ok，但我没有s3的账号可以测试，晚上打包一个给你测试一下。没有问题再发布

**Comment by imlinhanchao** [comment]
[markdown-image-pre-1.1.38.zip](https://github.com/imlinhanchao/vsc-markdown-image/files/14495830/markdown-image-pre-1.1.38.zip)
 试试这个。

**Comment by hzj629206** [comment]
<img width="265" alt="image" src="https://github.com/imlinhanchao/vsc-markdown-image/assets/1644620/e1b45751-f783-4c0c-a628-968931e5e05c">

无法配置 @imlinhanchao

**Comment by imlinhanchao** [comment]
你的vscode版本是多少？是解压后载入吗？

**Comment by hzj629206** [comment]
Version: 1.87.0 (Universal)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.1.0

<img width="248" alt="image" src="https://github.com/imlinhanchao/vsc-markdown-image/assets/1644620/b64f5211-c502-4df6-887b-f7d598e066e0">
解压后用VSIX安装的。

**Comment by imlinhanchao** [comment]
[markdown-image-pre-1.1.38.zip](https://github.com/imlinhanchao/vsc-markdown-image/files/14496233/markdown-image-pre-1.1.38.zip)
刚才打的包有点问题，用这个。

**Comment by hzj629206** [comment]
@imlinhanchao 感谢支持

经测试没有问题。在Bucket里面查看信息:

```
名称: 2ea5cff9f5ea66479752b1ba46c75bec2c5e885825442fcb3281fe7b9dfc5ef5.png
内容类型: image/png
```

**Comment by imlinhanchao** [comment]
好的~已发布。
