### ISSUE TITLE
Multiple image folder

### ISSUE THREAD

**Issue by fitiger** [imlinhanchao/vsc-markdown-image#13]
Hi, 

I need multiple image folders to store images that appeared in different sub-folder. 

Here is an example:
Project
├─ 20Oct
│  ├─ Img
│  │  ├─ a.png
│  │  └─ b.png
│  └─ readme.md
├─ 20Sep
│  ├─ Img
│  │  ├─ a.png
│  │  └─ b.png
│  └─ readme.md
├─ Img
│  ├─ a.png
│  └─ b.png
└─ Readme.md
Where each sub-folder has its own image folder. 

Thanks in advance!

**Comment by imlinhanchao** [comment]
You can set `markdown-image.local.path` to `./`
