### ISSUE TITLE
cloudflare配置之后，上传失败

### ISSUE THREAD

**Issue by imgwho** [imlinhanchao/vsc-markdown-image#133]
Authentication error Error: Authentication error at Cloudflare.<anonymous> (c:\Users\imgwho\.vscode\extensions\hancel.markdown-image-1.1.41\out\lib\cloudflare.js:39:23) at Generator.next (<anonymous>) at fulfilled (c:\Users\imgwho\.vscode\extensions\hancel.markdown-image-1.1.41\out\lib\cloudflare.js:5:58) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by imlinhanchao** [comment]
认证失败，请确认正确配置

**Comment by imgwho** [comment]
已解决，配置的时候，需要选择S3
