### ISSUE TITLE
在使用path变量时，会生成一个反斜杠的路径符

### ISSUE THREAD

**Issue by EasyEDA2021** [imlinhanchao/vsc-markdown-image#134]
![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/29702100/58bd2b16-caa7-47de-8592-42210339f5ed)
![image](https://github.com/imlinhanchao/vsc-markdown-image/assets/29702100/0c5f1e90-3624-4d4b-883f-c2cb45499815)

如图

**Comment by imlinhanchao** [comment]
更新到 1.1.42 再试试
