### ISSUE TITLE
Use filename in image folder name

### ISSUE THREAD

**Issue by davidbenque** [imlinhanchao/vsc-markdown-image#14]
I am looking to create one image folder for each file that I paste images into. A structure like this: 
```
├─ file_A_assets
│ ├─ image.png
│ └─ another_image.png
├─ file_A.md
├─ file_B_assets
│ ├─ image.png
│ └─ another_image.png
├─ file_B.md
and so on
```
I have tried using `"markdown-image.local.path": "${fileBasenameNoExtension}_assets"` but this gets used literally without substituting `${fileBasenameNoExtension}` for the current file name. Is there a way to do this with this extension?

**Comment by imlinhanchao** [comment]
Do you want to use the name of the currently edited markdown file as part of the folder name?  You can use the variable `${mdname}`.

**Comment by davidbenque** [comment]
Many thanks for the quick response. I managed to achieve what I had in mind with this setting: 
```
"markdown-image.base.fileNameFormat": "${mdname}_assets/${filename}"
```
So I was using the wrong variable and the wrong setting.

**Comment by sandianyiyuan** [comment]
我怎么贴出来是变量名呢：
![image](https://user-images.githubusercontent.com/22078056/106542087-1c2cae00-653e-11eb-8a1c-f58ac6a45914.png)

**Comment by imlinhanchao** [comment]
請貼一下你的配置。

**Comment by sandianyiyuan** [comment]
> 请贴一下你的配置。

![image](https://user-images.githubusercontent.com/22078056/106542449-d45a5680-653e-11eb-8961-1c2df10639b5.png)
![image](https://user-images.githubusercontent.com/22078056/106542481-e0461880-653e-11eb-940c-ccc51d051bf4.png)

**Comment by imlinhanchao** [comment]
`File Name Format` 更改為 `${mdname}${filename}/${HH}${mm}`   
`Local: Path` 更改為 `./`

**Comment by sandianyiyuan** [comment]
> `File Name Format` 更改為 `${mdname}${filename}/${HH}${mm}`
> `Local: Path` 更改為 `./`
搞定，3KS
