### ISSUE TITLE
怎么像 Typora 一样保存图片，按照文件名创建一个 assets 文件夹呢

### ISSUE THREAD

**Issue by xiaoxiyouran** [imlinhanchao/vsc-markdown-image#15]
![image](https://user-images.githubusercontent.com/25276073/101272664-36117500-37c9-11eb-8992-d9811c5be0da.png)
z这样配置好像不行。

**Comment by imlinhanchao** [comment]
看看这个 #14

**Comment by xiaoxiyouran** [comment]
> 看看这个 #14

![image](https://user-images.githubusercontent.com/25276073/101272872-4c203500-37cb-11eb-8f4c-64ec03ac9b9b.png)

但是这儿有个扩展名，请问有办法去掉吗？ 【这儿有个历史包袱，希望能和 typora 无缝对接】

**Comment by imlinhanchao** [comment]
OK，这是一个issue。刚刚修正了，你更新到1.0.10再确认看看。感谢反馈。

**Comment by imlinhanchao** [comment]
请问问题是否已解决？若已解决，请close issue。

**Comment by xiaoxiyouran** [comment]
> 请问问题是否已解决？若已解决，请close issue。

感谢大佬， 更新后，非常完美，向大佬学习，点赞点赞点赞 👍

**Comment by xiaoxiyouran** [comment]
大佬非常棒，这个插件应该是非常 good 了
