### ISSUE TITLE
希望可以设置本地图片路径的时候用变量

### ISSUE THREAD

**Issue by JackalZhao** [imlinhanchao/vsc-markdown-image#2]
希望可以设置本地图片路径的时候用变量

例如，在编辑 test.md 时，设置的本地的图片存储目录是 `./${mdname}_asset` ，那么，在粘贴图片时，就会将图片存储到 `./test_asset` 目录下了。

**Comment by imlinhanchao** [comment]
保存目录是可以使用变量的，在文件名加上 `/` 就可以了。比如 `${mdname}/${hash}`。

**Comment by imlinhanchao** [comment]
> 希望可以设置本地图片路径的时候用变量
> 
> 例如，在编辑 test.md 时，设置的本地的图片存储目录是 `./${mdname}_asset` ，那么，在粘贴图片时，就会将图片存储到 `./test_asset` 目录下了。

请问问题是否已解决，若已解决，此 Issue 将 Close。
