### ISSUE TITLE
有办法将图片放置到和markdown文件相同层级目录下吗？

### ISSUE THREAD

**Issue by XQDD** [imlinhanchao/vsc-markdown-image#20]
比如markdwown文件目录
/a/b/c/d.md
想把图片存到这个位置
/image/a/b/c/d/xxx.png

**Comment by XQDD** [comment]
通过现有变量貌似不能实现这个功能

**Comment by imlinhanchao** [comment]
目前的确没有这个功能。我找时间看看怎么做比较好。

**Comment by imlinhanchao** [comment]
@XQDD 已加入，更新至 1.0.12 版本，使用 `${path}` 變量。若可解決問題請關閉 Issue

**Comment by AldrinL** [comment]
> @XQDD 已加入，更新至 1.0.12 版本，使用 `${path}` 變量。若可解決問題請關閉 Issue

经测试使用${path}变量时，实际存储位置是当前打开的workspace下的image的目录，而不是打开的md文件的目录

我的预期是编辑/workspace/abc.md这个文件
图片存储到/workspace/media/abc/abc-1.png
设置中设为${path}/media/${mdname}/${mdname}

测试结果是存到了/workspace/images/media/${mdname}/${mdname}

**Comment by XQDD** [comment]
完美
