### ISSUE TITLE
remote host 无效

### ISSUE THREAD

**Issue by aybcoo** [imlinhanchao/vsc-markdown-image#21]
对于远程开发者无效 不能粘贴图片

**Comment by imlinhanchao** [comment]
目前扩展是基于PC系统脚本实现读取剪贴板，远程开发应该无法调用系统脚本。请问你的远程开发是通过 Web 版本的 VSCode 吗？

**Comment by aybcoo** [comment]
@imlinhanchao 通过vscode的远程开发
![image](https://user-images.githubusercontent.com/42240041/105834692-c15afa00-6005-11eb-9221-d71accc2b424.png)

**Comment by imlinhanchao** [comment]
@aybcoo 这种我还没有用过，你扩展是安装在本地的吗？选择的保存方式是什么？有没有报错信息。还是没有任何反应？

**Comment by aybcoo** [comment]
@imlinhanchao  对在本地安装的，用的Remote-SSH插件实现远程连接的，没有报错信息，没有反应

**Comment by imlinhanchao** [comment]
找時間我搭個環境試試。

**Comment by pipixia244** [comment]
同问这个问题，本地用windows端的vscode远程连接(通过Remote SSH插件)一linux服务器，并且在本地windows端安装了插件，插件界面已经显示在远程启用了扩展。但粘贴无效，没有报错也没有反应。运行时状态显示尚未激活。
![image](https://user-images.githubusercontent.com/56287117/159707234-727148ba-8f69-4ca1-bd0c-72d7caa9d2ff.png)
![image](https://user-images.githubusercontent.com/56287117/159707453-dd9935a1-a0a3-4c80-8a0a-f1e500f2bd8f.png)

**Comment by imlinhanchao** [comment]
插件需要系统脚本环境，目前还是无法支援 remote mode

**Comment by abctel** [comment]
> 插件需要系统脚本环境，目前还是无法支援 remote mode

同样需要这个ssh remote功能，不知道是否可以增加FTP上传的方式将图片上传到指定目录呢。

**Comment by whinc** [comment]
同样很需要这个功能，期待实现

**Comment by imlinhanchao** [comment]
@aybcoo @abctel @whinc @pipixia244 
现在扩展已经支援远程模式，可参考注意事项设置：
https://github.com/imlinhanchao/vsc-markdown-image/blob/master/README.zh-cn.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
