### ISSUE TITLE
复制网页上的文档和图片的时候 只能粘贴文字

### ISSUE THREAD

**Issue by aybcoo** [imlinhanchao/vsc-markdown-image#22]
有一个场景
小明希望将网页上选中的文字和图片复制下来，复制到markdown文件中
结果只复制下来文字，没有复制图片。

**Comment by imlinhanchao** [comment]
这个是专用图片的，你说的这个我得研究一下，富文本转义 markdown。有点意思。:smiley:

**Comment by aybcoo** [comment]
@imlinhanchao   word文档就可以实现既复制文字又复制图片

**Comment by imlinhanchao** [comment]
@aybcoo 这个和 Word 还是有很大差异的，VSCode 扩展的 API 的剪贴板就只支援到纯文本而已。:expressionless: 要想进一步基本都得通过系统的 API 去实现。

**Comment by imlinhanchao** [comment]
@aybcoo Hi~最新的 1.1.0 已经支援这个功能了，不过只支持在 Windows 使用。你可以试用看看。

**Comment by aybcoo** [comment]
@imlinhanchao  使用富文本的时候有乱码问题 老哥

**Comment by imlinhanchao** [comment]
@aybcoo 中文会乱码，还在想办法解决:joy:

**Comment by aybcoo** [comment]
好的，有时间我也研究研究


xingzhitan2019@163.com
 
发件人： Hancel Lin
发送时间： 2021-02-14 23:00
收件人： imlinhanchao/vsc-markdown-image
抄送： aybcoo; Mention
主题： Re: [imlinhanchao/vsc-markdown-image] 复制网页上的文档和图片的时候 只能粘贴文字 (#22)
@aybcoo 中文会乱码，还在想办法解决

**Comment by imlinhanchao** [comment]
試試這個，看起來中文不會亂碼了。但是如果中英文混合，在交界处還是會亂碼。你試試看你會不會。
https://github.com/imlinhanchao/vsc-markdown-image/releases/tag/pre-1.1.1

**Comment by aybcoo** [comment]
嗯嗯  少数字符会乱码
实验网址：https://www.zsythink.net/archives/1199
问题：遇到句号会乱码。



xingzhitan2019@163.com
 
发件人： Hancel Lin
发送时间： 2021-02-26 10:22
收件人： imlinhanchao/vsc-markdown-image
抄送： aybcoo; Mention
主题： Re: [imlinhanchao/vsc-markdown-image] 复制网页上的文档和图片的时候 只能粘贴文字 (#22)
@，看起碇形牟ya了。但是如果中英文混合，在交界处是ya。你看你
https://github.com/imlinhanchao/vsc-markdown-image/releases/tag/pre-1.1.1
―
