### ISSUE TITLE
粘贴图片存放本地一直上传

### ISSUE THREAD

**Issue by sandianyiyuan** [imlinhanchao/vsc-markdown-image#24]
粘贴图片存放本地一直上传上传是怎么回事呢，这样配的：
![image](https://user-images.githubusercontent.com/22078056/105940530-7f2dc900-6096-11eb-95bf-d2b5a99d4ce4.png)

**Comment by imlinhanchao** [comment]
請問是截圖還是複製圖片文件？

**Comment by sandianyiyuan** [comment]
截图，我用了Ditto，有时候从Ditto的复制历史中粘贴不知道算是截图还是复制。都没有成功过

**Comment by imlinhanchao** [comment]
@sandianyiyuan 了解，我弄个相同环境测试一下。

**Comment by imlinhanchao** [comment]
我確實有看到沒有保存的現象，但不會一直 Loading，請試試手動安裝這個版本是否有解決問題。
[markdown-image-1.0.13.zip](https://github.com/imlinhanchao/vsc-markdown-image/files/5891124/markdown-image-1.0.13.zip)

**Comment by sandianyiyuan** [comment]
好的，我试一下，感谢。

**Comment by imlinhanchao** [comment]
@sandianyiyuan 已將更改發佈到市場，若確認可以解決問題，建議卸載手動安裝的擴展從市場重新安裝，以便自動獲取後續的更新。

**Comment by weibobo** [comment]
@imlinhanchao  我安装的最新的版本，已经是uploading, 环境是windows7, vscode: 1.52.1

**Comment by weibobo** [comment]
不管是直接的复制图片或者是剪切板

**Comment by imlinhanchao** [comment]
> @imlinhanchao 我安装的最新的版本，也是存放本地，默认配置，一直是uploading, 环境是windows7, vscode: 1.52.1

Windows 7? 因爲是基於系統脚本獲取圖片，我測試看看，有可能是脚本不兼容 Windows 7。

**Comment by weibobo** [comment]
估计是这个原因，我看是调用的powershell这种

**Comment by imlinhanchao** [comment]
> 估计是这个原因，我看是调用的powershell这种
試試這個是否可以解決問題：
[markdown-image-1.0.14.zip](https://github.com/imlinhanchao/vsc-markdown-image/files/5893089/markdown-image-1.0.14.zip)

**Comment by imlinhanchao** [comment]
@sandianyiyuan 若問題已解決，請 Close Issue。謝謝！

**Comment by sandianyiyuan** [comment]
本地粘贴可以了。
