### ISSUE TITLE
文件保存路径自定义

### ISSUE THREAD

**Issue by doge-liang** [imlinhanchao/vsc-markdown-image#27]
我的文档写在 `source\_posts\a\b\file.md` 中，我希望能够将图片保存至 `source\assets\a\b\<hashcode>.jpg` 。`${path}` 的值为 `source\_post\a\b` 我想把中间的 `_post` 换成 `assets`  ，请问有没有办法通过 `DIY.path` 实现呀？我不太清楚 `DIY.path` 里面的函数是如何工作的。

**Comment by imlinhanchao** [comment]
`DIY.path` 是可以让你自己实现文件保存路径的方式，你可以自己写一个类似[这个一样](https://github.com/imlinhanchao/vsc-markdown-image/blob/master/asserts/sample.js)的 Node.js 代码文件。然后将文件路径填写在设置里面。这样在`粘贴图片`图片时，就会执行里面的代码。其中有三个参数：
- filePath: 粘贴的图片的路径。
- savePath: 通过`fileNameFormat`计算出来的保存路径，要自己定义可以不使用。
- markdownPath：要粘贴图片的 Markdown 文件路径。
那么对于你这个需求，你应该只要把下面的 Code 保存为 Javascript 文件。然后把路径填入 `DIY.path` 就可以解决了：

```javascript
const path = require('path');
const fs = require('fs');

module.exports = async function(filePath, savePath, markdownPath) {
    savePath = markdownPath.replace(/_posts/, 'assets');
    fs.copyFileSync(filePath, savePath);
    return path.relative(path.dirname(markdownPath), savePath);
}
```

**Comment by doge-liang** [comment]
非常感谢您的帮助，您的插件太好用了
