### ISSUE TITLE
路径和文件名的中文无法识别，出现乱码

### ISSUE THREAD

**Issue by ryan00zou** [imlinhanchao/vsc-markdown-image#28]
当需要复制图片的路径和文件名含有中文时，会出现乱码无法导入。

提示如下：
保存文件失败了：ENOENT: no such file or directory，copyfile "D\610-???\611-
???\assets\???.jpg'->
'd\Documents\Ryan笔记\assets\???jpg'
来源：Markdown lmage（扩展）

**Comment by imlinhanchao** [comment]
问题已解决，请更新到 1.1.1 版本。

**Comment by ryan00zou** [comment]
> 
> 
> 问题已解决，请更新到 1.1.1 版本。

谢谢大大回复。

下午尝试把powershell的注册表，加了CodePage值65001，是可以粘贴了的。虽然粘贴后文件里的路径和文件名会被转换成含有"%3A"这种的，但是也算能正常使用。

但更新后，现在粘贴，只会在状态栏“提示激活扩展，正在上传”，然后就没有任何反应了。

**Comment by imlinhanchao** [comment]
@ryan00zou 建议你把添加的修改移除，因为我已经修改脚本解决了这个问题，可能你的修改会让我的更新没有效果。

**Comment by ryan00zou** [comment]
> 
> 
> @ryan00zou 建议你把添加的修改移除，因为我已经修改脚本解决了这个问题，可能你的修改会让我的更新没有效果。

试过了，把添加的注册表项删除后也没有反应。回撤安装1.0.14版本，可以粘贴。文件路径显示如下：

![图 1](assets/%E5%BE%AE%E4%BF%A1%E4%BA%8.jpg)

**Comment by imlinhanchao** [comment]
@ryan00zou 这个路径是正确的，因为URL要做encode处理。

**Comment by ryan00zou** [comment]
> 
> 
> @ryan00zou 这个路径是正确的，因为URL要做encode处理。

好的，谢谢。那就先用1.0.14版本了。
