### ISSUE TITLE
上传的同时，也在本地保存？

### ISSUE THREAD

**Issue by JiandanDream** [imlinhanchao/vsc-markdown-image#29]
如题，上传到图床的时候，希望也在本地保存一份。
请问是否有考虑过支持这样的功能？
或者使用 DIY 方式，我能如何实现上述功能？

**Comment by imlinhanchao** [comment]
這個應該要通過 DIY 功能來做了，也是屬於比較小衆的需求。你是要用哪個圖床。

**Comment by JiandanDream** [comment]
> 這個應該要通過 DIY 功能來做了，也是屬於比較小衆的需求。你是要用哪個圖床。

要使用 SM.MS 的图床
嗯嗯 比较小众，能否告知可以如何实现吗？我自己试试看。

**Comment by imlinhanchao** [comment]
> > 這個應該要通過 DIY 功能來做了，也是屬於比較小衆的需求。你是要用哪個圖床。
> 
> 要使用 SM.MS 的图床
> 嗯嗯 比较小众，能否告知可以如何实现吗？我自己试试看。

可以做到，不過得自己實現圖床的上傳功能了。可以參考這裏 #27

**Comment by JiandanDream** [comment]
> > > 這個應該要通過 DIY 功能來做了，也是屬於比較小衆的需求。你是要用哪個圖床。
> > 
> > 
> > 要使用 SM.MS 的图床
> > 嗯嗯 比较小众，能否告知可以如何实现吗？我自己试试看。
> 
> 可以做到，不過得自己實現圖床的上傳功能了。可以參考這裏 #27

好的，感谢感谢！

**Comment by imlinhanchao** [comment]
有遇到問題，就再回復咯~

**Comment by imlinhanchao** [comment]
@JiandanDream Hello~請問有成功嗎？或是遇到什麽問題。

**Comment by imlinhanchao** [comment]
1.1.31 版本已支援
