### ISSUE TITLE
Encode spaces as '%20' in images paths

### ISSUE THREAD

**Issue by Akiat** [imlinhanchao/vsc-markdown-image#3]
Hi and thank you for this extension :)

Just a little issue: If we want to use a path or a filename with spaces, the image is not displayed. In fact, spaces are not allowed in urls. But we can url-encode them to get a %20 and then it works perfectly :)

Have a good day !

**Comment by imlinhanchao** [comment]
The issue was fixed just now. You can update to 1.0.5 check it.  :)

**Comment by Akiat** [comment]
Perfectly works ! Thanks :)
