### ISSUE TITLE
Coding貌似上传不了

### ISSUE THREAD

**Issue by XQDD** [imlinhanchao/vsc-markdown-image#30]
仓库：
https://xqdd.coding.net/p/storage/d/storage/git
Token：
9fc74824f7e4cb6a5bb7c2fc15a0fd7cdb2c412e（临时用的不用担心）

**Comment by XQDD** [comment]
![image](https://user-images.githubusercontent.com/20871761/112572359-ff697400-8e24-11eb-838e-2f658bce3230.png)

**Comment by imlinhanchao** [comment]
實測可用。請問你的擴展是最新的嗎？

**Comment by XQDD** [comment]
> 實測可用。請問你的擴展是最新的嗎？

经测试，这个路径不行，应该是`${path}`的锅
`/images/${path}/${mdname}/${hash}`
![image](https://user-images.githubusercontent.com/20871761/112576486-55dab080-8e2d-11eb-9bb6-dfc38682a2fa.png)

待上传图片文件名含有中文也不行  
`参数格式转换调用栈.jpg`
![image](https://user-images.githubusercontent.com/20871761/112576464-4bb8b200-8e2d-11eb-8198-65e472f7b620.png)

**Comment by imlinhanchao** [comment]
請更改為 `images/${path}/${mdname}/${hash}`。中文文件名我再確認。

**Comment by imlinhanchao** [comment]
中文名問題已解決，請更新至 1.1.2 。謝謝！

**Comment by XQDD** [comment]
`images/${path}/${mdname}/${timestramp}`这个也不行

**Comment by XQDD** [comment]
![image](https://user-images.githubusercontent.com/20871761/112587499-a1df2280-8e38-11eb-8bf6-7844bc0aebd7.png)
也可能你说明写错了

**Comment by XQDD** [comment]
timestramp -> timestamp?

**Comment by imlinhanchao** [comment]
拼寫確實有誤，不過我實測可用。你插入后的路徑是什麽？

**Comment by XQDD** [comment]
文件路径：工作记录/2021-03/禁用swagger后枚举值转枚举类型功能失效分析.md

**Comment by XQDD** [comment]
## `images/${path}/${mdname}/${hash}`  上传后路径有误
![image](https://user-images.githubusercontent.com/20871761/112588246-08b10b80-8e3a-11eb-8549-cef4e61825d6.png)

## `images/${path}/${mdname}/${timestramp}` 不能上传
![image](https://user-images.githubusercontent.com/20871761/112588346-2ed6ab80-8e3a-11eb-8bfa-9235e571f873.png)

**Comment by XQDD** [comment]
多了一个%5c是windows原因？他的url解码是反斜杠\

**Comment by imlinhanchao** [comment]
我知道問題了，稍後更新一版。😂

**Comment by imlinhanchao** [comment]
已發佈，更新至 1.1.3 即可。

**Comment by XQDD** [comment]
可以了，非常感谢
