### ISSUE TITLE
建议加入base64图片方式

### ISSUE THREAD

**Issue by XQDD** [imlinhanchao/vsc-markdown-image#31]
RT

**Comment by imlinhanchao** [comment]
已加入，更新到 1.1.4 版本，选择 `Data URL`。

**Comment by XQDD** [comment]
![image](https://user-images.githubusercontent.com/20871761/112775872-b148b080-9070-11eb-9cc4-9e729229f6ce.png)

描述可能可能需要改一下

**Comment by imlinhanchao** [comment]
已修正。謝謝！

**Comment by msdemt** [comment]
麻烦问下，我是用 data url 方式后，md文件预览无法看到图片，该怎么解决呢？

**Comment by msdemt** [comment]
使用data url方式上传图片后，图片引用的方式是：
![图1](1652663110649)
需要将小括号改为中括号，才能正确显示图片：
![图1][1652663110649]  

而且目前dataurl方式还不支持自定义名${prompt}，只能用hash

@imlinhanchao 希望能够优化下，谢谢
