### ISSUE TITLE
自定义本地图片目录的问题

### ISSUE THREAD

**Issue by silvergp** [imlinhanchao/vsc-markdown-image#32]
我希望粘贴进去的图片，保存到当前文件的同名目录下
我是这么设置的
![image](https://user-images.githubusercontent.com/22089160/113076298-4da1bd00-9201-11eb-8213-7f8061e6dc04.png)
但文件的存储目录却是
![image](https://user-images.githubusercontent.com/22089160/113076335-63af7d80-9201-11eb-8026-adfb6491405b.png)
是我哪里设置的不对吗？

**Comment by imlinhanchao** [comment]
再 File Name Format 前面加上 `${filename}/`

**Comment by silvergp** [comment]
多谢！好使了
