### ISSUE TITLE
Don't log everything by default

### ISSUE THREAD

**Issue by Tyriar** [imlinhanchao/vsc-markdown-image#33]
The extension is quite noisy in devtools, which will get in the way for other extension authors/vscode devs like myself

![image](https://user-images.githubusercontent.com/2193314/114422256-f4277f80-9b6a-11eb-8fe9-a6f2781ed860.png)

This is typically solved by having a `.logLevel` setting, which you can hardcode to be verbose by default while you're debugging the extension.

**Comment by imlinhanchao** [comment]
Thanks for your suggestion, I will update it soon.

**Comment by imlinhanchao** [comment]
The version 1.1.6 was updated log level. you can check it.
