### ISSUE TITLE
Improve name on paste

### ISSUE THREAD

**Issue by Tyriar** [imlinhanchao/vsc-markdown-image#34]
Right now the name is just a big hex string like `aa2266d3e0b3e4d412c514f0d777d0e01362384c8857c1f6b43e805235cb1b0e.png`, I'd prefer if it derived the name based on the file in which it was pasted. For example pasting into a file `a/b/myfile.md` I'd like to be named something like one of these:

- `myfile-1.png`
- `myfile-<hex>.png`

**Comment by imlinhanchao** [comment]
you can setting `file name format` to `{mdname}-${hex}`.

**Comment by Tyriar** [comment]
Perfect, thanks!
