### ISSUE TITLE
Pasting an identical image fails

### ISSUE THREAD

**Issue by Tyriar** [imlinhanchao/vsc-markdown-image#35]
The hex string seems to be derived from the file's contents, and it ends up failing when you paste the same image into the same file:
![image](https://user-images.githubusercontent.com/2193314/114422913-8b8cd280-9b6b-11eb-90c6-1570cb65353c.png)

It should either reuse the same file, or upload a new copy.

**Comment by imlinhanchao** [comment]
If you paste the same file, it will be prompted whether to replace it. Your screenshot look like does not found any pictures on the clipboard.
![](https://user-images.githubusercontent.com/1502581/114486091-bea09600-9c3f-11eb-98a3-0b90fae8d5e9.png)

**Comment by Tyriar** [comment]
You're right 😅
