### ISSUE TITLE
本地圖片儲存位置，請添加變數方式

### ISSUE THREAD

**Issue by WS-HS** [imlinhanchao/vsc-markdown-image#36]
以前使用**ZIMWIKI 與 TYPORA**
最近想移轉到VSC
但一直尋找不到像樣的圖片插入外掛
您這外掛是目前還算比較合用的了
但有個問題
以很多人使用的TYPORA
與編寫WIKI方式來說
很多人的需求是必須**將圖片或附件放置於文件同名的資料夾**

結構如:
(個人因為習慣問題，所以使用這種方式)

file1.md
[file1]
----file1.png
----file2.md
----[file2]
--------file2.png

或
(避免文件與圖檔可能於同資料夾，將附件確實與文件方離的方式)

file1.md
[file1.附件]
----file1.png
[file1]
----file2.md
----[file2.附件]
--------file2.png

以TYPORA為例
TYPORA使用的路徑是
**./${filename} asset
./${filename}**
這種方式 
**${filename} 為當前編輯文件名**

將所有圖片的方式表面看似合理
(在網站上合理有其歷史背景
一開始是為了每頁都顯示的圖片，例如按鈕、網站圖標，所以出現了images資料夾放置這些不只屬於單一文件的雜圖，這些會被整批網頁共同引用的圖檔，
但後來的許多人搞不清楚狀況，一股腦地把所有文件的圖片都塞進images，還自以為這是什麼天殺的世界規範)
但其實在本地檔案與有大量圖片需求與文件附件管理上
這會是種極度嚴重不合理的選擇。
例如很顯然的，當要刪除一個文件時，你是要怎麼簡單的區分那些圖片確實可以刪除 ?
ok~我知道... ~再寫一個沒事多搞事的外掛來分析什麼圖片沒用到~ (如果有上千的文件檔，就為了砍個文件算到死吧...)

所以總之。是否能將本地儲存路徑，加上使用當前文件名稱(不含附檔名)的變數的功能呢
至少目前來說，只找到您這個貼上圖片的外掛算得上是方便，但就差卡在儲存方式的問題了
感謝您

另外~題外話的問一下
在VSC上，用拖曳的方式加入markdown圖片是不可能實現的嗎?
因為似乎完全沒有外掛能做到這點?

**Comment by imlinhanchao** [comment]
当前文件名请使用变数 `${mdname}`

**Comment by imlinhanchao** [comment]
拖拽的我找时间研究一下

**Comment by imlinhanchao** [comment]
确认不可实现，此部分 VSCode 官方尚未支援。  
https://github.com/Microsoft/vscode/issues/5240

**Comment by WS-HS** [comment]
> 当前文件名请使用变数 `${mdname}`

抱歉，之前沒寫得足夠清楚。其實我試過了。
問題是變數轉換並未轉換而是被直接以純文字字串方式處理了
也就是變數失效
附上截圖也許更容易理解一點
請見附件圖檔

[本地設定](https://imgur.com/9yhOi2e)

[貼上結果](https://imgur.com/uxdSdto)

**Comment by imlinhanchao** [comment]
变数只能写在 file name format 中，参考 issue https://github.com/imlinhanchao/vsc-markdown-image/issues/32

**Comment by WS-HS** [comment]
> 变数只能写在 file name format 中，参考 issue #32

原來是必須這麼使用。總算成功了^^~。
另外，建議下次改版時，在本地路徑的說明文字上加上
如需以文件名資料夾儲存(例如:${mdname}/${filename})，請於最上方的 File Name Format 設定中寫入。此欄不支援原變數。

也許這樣下次就不會有人跟我一樣再問了。哈

最後
非常感謝您抽空回答。謝謝!

**Comment by imlinhanchao** [comment]
好的，确实有不少人有这种疑问。:smile:

**Comment by WS-HS** [comment]
剛剛才注意到，${mdname}:作為文件夾名稱在md顯示的是編碼過的
我了解如需上傳在網路服務上這是為什麼，但能再加個未編碼直接以檔名寫入的變數讓人使用嗎?

因為我都是本地文件居多，網路存儲限制對我影響不大，而且有時也會引用其他位置的圖檔，並且會有用其他移動設備的markdown編輯器APP修改的需求，所以直接明碼寫的方式對我會較好管理與閱讀。感謝

**Comment by imlinhanchao** [comment]
确实是为了放在网络服务上，因为许多是用于 GitHub Page 的博客。我去将这一项目做成可选项吧。你不需要编码去掉勾选即可。

**Comment by WS-HS** [comment]
好的~非常感謝 👍  : )

**Comment by imlinhanchao** [comment]
@WS-HS 已经加入，可以通过更新到 1.1.7 切换这个选项。

![image](https://user-images.githubusercontent.com/1502581/114977638-95d80500-9eba-11eb-98a1-cab0ec11cd67.png)

**Comment by WS-HS** [comment]
> @WS-HS 已经加入，可以通过更新到 1.1.7 切换这个选项。
> 
> ![image](https://user-images.githubusercontent.com/1502581/114977638-95d80500-9eba-11eb-98a1-cab0ec11cd67.png)

剛剛測試成功了 😄 
非常感謝!! 👍
