### ISSUE TITLE
图片粘贴的路径不能使用vscode的宏

### ISSUE THREAD

**Issue by LegerYo** [imlinhanchao/vsc-markdown-image#37]
将图片路径改为${file},${currentFileDir}等都不会解析成vscode的路径，希望能够得到支持

**Comment by imlinhanchao** [comment]
vscode 路径是指什么？你看看 `${path}` 能不能符合你的需求。

**Comment by LegerYo** [comment]
![image](https://user-images.githubusercontent.com/66580331/115133492-3a815080-a03b-11eb-83cb-b9b2dd386295.png)
这些路径变量都不能使用

**Comment by LegerYo** [comment]
> vscode 路径是指什么？你看看 `${path}` 能不能符合你的需求。

**Comment by imlinhanchao** [comment]
这些是 vscode 内部的配置路径，和我的扩展没有关系。扩展支援的变量要看扩展的设置界面。你具体是要什么样变量？

**Comment by LegerYo** [comment]
很多扩展都支持使用这些变量创建目录。
我想根据每个md文件的名字创建一个文件夹单独存放图片，而不是所有md文件的图片都放在一个文件夹中。比如file1.md的图片放入file1_img文件夹中，file2.md的图片放入file2_img文件夹中。使用vscode的${currentFileNameWithoutExt}_img就能很方便实现

**Comment by imlinhanchao** [comment]
你要的变量就是 `${mdname}`

**Comment by LegerYo** [comment]
> 你要的变量就是 `${mdname}`

![image](https://user-images.githubusercontent.com/66580331/115134059-a796e500-a03f-11eb-91bb-647108fe706a.png)
好像没有效果

**Comment by imlinhanchao** [comment]
变量只能写在 file name format，请参考 issue #32

**Comment by LegerYo** [comment]
十分感谢，解决了

> 变量只能写在 file name format，请参考 issue #32

**Comment by imlinhanchao** [comment]
close #37
