### ISSUE TITLE
'DIY.path' example doesn't works

### ISSUE THREAD

**Issue by Akiat** [imlinhanchao/vsc-markdown-image#4]
Hi,

A second issue, but maybe I'm doing it wrong: The DIY.path given example doesn't works. I got this error:

```
Upload File Failed: Cannot find module 'const path = require('path'); module.exports = async function(filePath, savePath, markdownPath) { return path.relative(path.dirname(markdownPath), filePath); }'

Require stack: 
- c:\Users\User\.vscode\extensions\hancel.markdown-image-1.0.4\out\lib\define.js 
- c:\Users\User\.vscode\extensions\hancel.markdown-image-1.0.4\out\lib\uploads.js 
- c:\Users\User\.vscode\extensions\hancel.markdown-image-1.0.4\out\lib\utils.js 
- c:\Users\User\.vscode\extensions\hancel.markdown-image-1.0.4\out\extension.js 
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js 
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js 
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
```

My end goal is to store my image in the 'images' directory, but on the same sub-path than the markdown file. E.g.: if my md file is in 
`/a/sub/folder/markdown_file.md`
I would like my image in:
`/images/a/sub/folder/markdown_file_8925.jpg`

By the way, the rand function for the filename doesn't works (it appends NaN). I don't know if you want that I open a new issue for this ?

Thanks again :)

**Comment by imlinhanchao** [comment]
The sample code is not used to fill in DIY.path.  You should write it in a [file](https://github.com/imlinhanchao/vsc-markdown-image/blob/master/asserts/sample.js), and then fill the file path into DIY.path.

**Comment by imlinhanchao** [comment]
The rand function issue was fixed just now. You can update to 1.0.5 check it.  Thank you for your feedback. :)

**Comment by Akiat** [comment]
Perfect, thank you for the fix, and my bad for my misunderstood of the DIY path :p
