### ISSUE TITLE
Ubuntu not work. Paste image but no reponse.

### ISSUE THREAD

**Issue by forechoandlook** [imlinhanchao/vsc-markdown-image#43]
install xclip  and this vscode plugin 
but fail to paste images

**Comment by imlinhanchao** [comment]
Are your copy a image file ? Please execute command `xclip -selection c -o`. give me the output.

If you are paste a screenshot. Please execute command `xclip -selection clipboard -target image/png -o `.

**Comment by forechoandlook** [comment]
Actually, the image is in my clipboard. But I know the problem. I use vscode to control my remote server. Therefore, my clipboard in my client not server,  and xclip not work. 
I am so sorry to trouble you.
Do you have any suggestion?

**Comment by imlinhanchao** [comment]
This extension is not support remote mode yet. I'm sorry I can't help you.

**Comment by forechoandlook** [comment]
Anyway, very happy to get your response.

**Comment by missuor** [comment]
第二个问题为linux环境下面上传图片不成功，对应编辑更新了linux.sh文件。
版本: 1.78.2
提交: b3e4e68a0bc097f0ae7907b217c1119af9e03435
日期: 2023-05-10T14:47:05.613Z
浏览器: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.78.2 Chrome/108.0.5359.215 Electron/22.5.2 Safari/537.36

Linux环境上面通过vscode安装完成后的linux.sh里面文件换行为CRLF，通过vscode打开linux.sh，将换行调整为LF后重新保存后能够正确上传。

我在这个pr里面处理了，但是因为定位问题的原因是文件换行付CRLF修改为LF，我不确定我的提交是否能够覆盖掉文件换行符
https://github.com/imlinhanchao/vsc-markdown-image/pull/98

**Comment by imlinhanchao** [comment]
The extension was support remote mode. You can check [this](https://github.com/imlinhanchao/vsc-markdown-image/tree/master#notice).
