### ISSUE TITLE
希望可以支持ipynb格式的文件

### ISSUE THREAD

**Issue by Demcorazy** [imlinhanchao/vsc-markdown-image#44]
希望可以支持ipynb格式的文件，或者可以自定义在哪些文件里启用此插件

**Comment by imlinhanchao** [comment]
ipynb 的插入圖片代碼語法和 Markdown 一樣嗎？

**Comment by Demcorazy** [comment]
> ipynb 的插入圖片代碼語法和 Markdown 一樣嗎？

是的，完全一样，ipynb文件中Markdown代码块完整支持Markdown语法

**Comment by imlinhanchao** [comment]
ok，那我先加入這個文件的支援，自定義的我要確認一下是否有辦法支援。

**Comment by Demcorazy** [comment]
好的，非常感谢😃

**Comment by imlinhanchao** [comment]
已經更新，可在 1.1.12 版本使用。另外由於 ipynb 特殊性，只能在 Text Editor 和 jupyter notebook(preview) 模式下粘貼圖片。另外，jupyter notebook(preview) 模式只能支持快捷鍵（Shift + Alt + V）進行粘貼。

**Comment by Demcorazy** [comment]
可以用了，这速度太赞了👍👍👍
