### ISSUE TITLE
可以上传，但是插入的链接仅是文件名

### ISSUE THREAD

**Issue by atlasbioinfo** [imlinhanchao/vsc-markdown-image#46]
首先非常感谢这个插件，从此我就用vscode写博客了=-=
我配置了七牛云，可以正常上传，但是插入到文档中的时候仅是文件名，需要手动添加链接才能显示（难道是我配置错了？因为我看七牛云的配置里面没有配置路径这个选项）。

比如：
图片叫test.jpg，上传到七牛域名pic.test.com, 链接为https://pic.test.com/test.jpg
然鹅插入到vscode里面为test.jpg，需要手动加上前面的链接。

如果是我没配置好，求帮助，非常感谢~

**Comment by imlinhanchao** [comment]
应该不会，请提供一下你的配置。

**Comment by imlinhanchao** [comment]
你可能要確認一下 `markdown-image.qiniu.domain` 是否有配置。

**Comment by atlasbioinfo** [comment]
我发现了：
之前我domain设置的是 a.b.com，能上传但是不能插入；
我改成https://a.b.com 就可以了...

**Comment by imlinhanchao** [comment]
好的，那就應該沒有問題。
