### ISSUE TITLE
Coding uploading hangs

### ISSUE THREAD

**Issue by callmexss** [imlinhanchao/vsc-markdown-image#47]
When uploading using coding as picuture bed, it hangs and raise error as below:

![image](https://user-images.githubusercontent.com/29946780/131862279-3c47a634-e5f2-457a-aaa7-e524bb1798da.png)

**Comment by imlinhanchao** [comment]
Coding 的 API 有变化。我需要研究一下。

**Comment by imlinhanchao** [comment]
I was fixed. please update to 1.1.14

**Comment by callmexss** [comment]
> I was fixed. please update to 1.1.14

It worked. Thanks!
