### ISSUE TITLE
文件名字格式字符串中日期比实际多一天

### ISSUE THREAD

**Issue by msdemt** [imlinhanchao/vsc-markdown-image#5]
首先感谢作者提供这么方便的插件，使用过程中发现一个小问题：

vscode中配置的 File Name Format为 ${YY}${MM}${DD}-${filename}

2020年7月16日使用shift + alt + v 上传一张图片，图片的名字为 `![图 1](20200717-pic_1594880936773.png)` 

图片的名字中日期比实际日期多一天，实际日期为16号，图片名字日期为17号

希望能够解决

谢谢

**Comment by imlinhanchao** [comment]
哦哦！可能是時區的原因。我晚上看看。

**Comment by imlinhanchao** [comment]
问题已修正。

**Comment by msdemt** [comment]
感谢
