### ISSUE TITLE
How to make it work in WSL?

### ISSUE THREAD

**Issue by tariusagi** [imlinhanchao/vsc-markdown-image#54]
First, a big thank to you for such an amazing extension, which I've looked for a long time.

Next, my problem: I frequently use VS Code in WSL2, and this extension doesn't work. My WSL distro is Ubuntu 20.04 LTS running in a Windows 10 host. VS Code was installed on the Windows host and connect to its server counter-part in WSL. I installed xlip as per the guide, but it still does not work. I guess there's something about the clipboard in WSL. Is there anything todo?

**Comment by imlinhanchao** [comment]
I'm very sorry. The extension does not work under WSL yet. Because it needs to call the script of the system to get the pictures in the clipboard.

**Comment by tariusagi** [comment]
OK, I understand that. Still hope you will make it work with WSL soon.

**Comment by renantmagalhaes** [comment]
Hi! 

Any news on this? I would love to have this function over WSL
