### ISSUE TITLE
配置上传coding时无法通过正则匹配

### ISSUE THREAD

**Issue by lemonkiller** [imlinhanchao/vsc-markdown-image#57]
![image](https://user-images.githubusercontent.com/9989574/153791703-56bf90a4-a8f4-47a0-9213-1f71a581134f.png)

**Comment by imlinhanchao** [comment]
應該是倉庫網頁的地址，而非 git 的地址

**Comment by lemonkiller** [comment]
万万没想到,感谢.
但接下来又报这个错误:
![image](https://user-images.githubusercontent.com/9989574/153805075-9eb1ab4c-7579-479c-ba26-5c14d882a269.png)

**Comment by imlinhanchao** [comment]
有沒有把項目設置成爲開源的狀態？

**Comment by lemonkiller** [comment]
已经设置了开源仓库

**Comment by lemonkiller** [comment]
可以了,我发现把不开源的改开源不行,必须一开始就设置开源
感谢!

**Comment by imlinhanchao** [comment]
好的~
