### ISSUE TITLE
Absolute path support

### ISSUE THREAD

**Issue by TianYang-TY** [imlinhanchao/vsc-markdown-image#58]
Hi, thanks for your excellent extension.

I'm trying to use absolute path in `Local: Path`, but it seems relative path only.

Personally, I usually store my images in Onedrive as `C:/Users/username/Onedrive/` or `~/Onedrive`. I've tried both, but the extension keeps copying the image to `${path}`.

Is there any way to use absolute paths, or isn't it supported yet? Thank you.

**Comment by imlinhanchao** [comment]
That was a bug. I will fixed tomorrow. Thanks your feedback.

**Comment by imlinhanchao** [comment]
You can update to 1.1.18 to support it.

**Comment by TianYang-TY** [comment]
> 

It works fine now, thank you very much!
