### ISSUE TITLE
1.1.18 本地图片保存BUG

### ISSUE THREAD

**Issue by HuangMJJJJJ** [imlinhanchao/vsc-markdown-image#59]
1.1.18 版本，本地图片不会保存在打开文件夹根目录的相对位置，而是保存在了磁盘根目录的相对位置

**Comment by imlinhanchao** [comment]
请问你的 Path 设置什么？

**Comment by HuangMJJJJJ** [comment]
"markdown-image.local.path": "/asset/",
 "markdown-image.base.fileNameFormat": "${mdname}_${timestamp}"
下图中图2为1.1.17版本的正确保存地址
图1为1.1.18版本的错误保存地址
![image](https://user-images.githubusercontent.com/71648539/155277394-6a4627f9-f7f8-43f2-832a-d196e9a7d68c.png)

**Comment by imlinhanchao** [comment]
已修正，更新至 1.1.19 可解。

**Comment by HuangMJJJJJ** [comment]
![image](https://user-images.githubusercontent.com/71648539/155283132-884c1fd0-a188-4ab0-a7ac-a2ddaf8f78e0.png)
非常棒！感谢，已经可以了
