### ISSUE TITLE
[编码问题]非常好用的插件,但是在Windows下好像有编码的问题

### ISSUE THREAD

**Issue by luv39** [imlinhanchao/vsc-markdown-image#6]
在Windows下粘贴的链接会像这样
![image](https://user-images.githubusercontent.com/30774614/87956337-8077ab00-cae1-11ea-9067-5f10706173ce.png)
冒号和中文都变成了乱码,在vscode中预览没有问题,但是使用其他软件预览的时候图片就会显示不出来

**Comment by imlinhanchao** [comment]
中文正确应该是要编码的，冒号的问题我看看，不应该被编码。另外你用于验证的其它软件是什么，我一并确认一下兼容性。

**Comment by luv39** [comment]
我是同步到手机端查看的，坚果云

**Comment by imlinhanchao** [comment]
OK，我注意到你是用仓库的图床，请问仓库有设置成公开的状态吗？

**Comment by luv39** [comment]
公开了，而且手动把%3A改成冒号之后就可以预览到图片了

**Comment by imlinhanchao** [comment]
好的，看起来就是冒号被转义造成的，我明天改一下。

**Comment by imlinhanchao** [comment]
问题已修正，请更新到版本 1.0.7 。

**Comment by luv39** [comment]
感谢
