### ISSUE TITLE
上传图片到Gitee仓库

### ISSUE THREAD

**Issue by winner106** [imlinhanchao/vsc-markdown-image#60]
请问可以上传到gitee仓库吗？或者给一个自定义上传到gitee的代码示范，非常感谢！

**Comment by imlinhanchao** [comment]
gitee 的 好像有防盗链哦

**Comment by winner106** [comment]
> gitee 的 好像有防盗链哦，你有试过可以外链吗？

现在很多人用gitee public做图床，配合picgo上传的，体验不错。如果能结合你的插件，实现在vscode上粘贴上传的话，体验就更好了。

[https://zhuanlan.zhihu.com/p/102594554](https://zhuanlan.zhihu.com/p/102594554)

**Comment by imlinhanchao** [comment]
Gitee 已经不能用作图床了
