### ISSUE TITLE
本地的图片存储设置使用变量

### ISSUE THREAD

**Issue by skoweb** [imlinhanchao/vsc-markdown-image#62]
可以在设置markdown-image.local.path中改成使用变量吗？我在本地储存图片全放一个文件夹里太乱了，想根据md文件名自动创建文件夹存放

**Comment by imlinhanchao** [comment]
看看 #32

**Comment by skoweb** [comment]
可以了，但是这样设置一般人想不到，希望大佬以后可以改成直接在path中设置
