### ISSUE TITLE
粘贴图片时出现格式错误

### ISSUE THREAD

**Issue by SydianAndrewChen** [imlinhanchao/vsc-markdown-image#63]
![image](https://user-images.githubusercontent.com/65159293/162390041-baf04f18-607e-48e5-9698-dd2e13b04c96.png)
如图是我在插件中的设定，但是在粘贴图片之后，reference path会变成如下格式
![image](https://user-images.githubusercontent.com/65159293/162390400-1a39dc6b-25b8-4e42-a121-892bea22ab08.png)
想问下是在Windows下自动转换成绝对路径导致的吗，如果是的话有什么方法可以关闭这个功能呢，我就是想要直接reference到`/images/${mdname}`下的

**Comment by SydianAndrewChen** [comment]
> 確認一下你的插件版本是否是 1.1.19，這個版本已經有解決了這個問題才對

可以确认是1.1.19
![image](https://user-images.githubusercontent.com/65159293/162392674-782fc2f4-e84e-49a6-a951-dba895089a0c.png)

**Comment by imlinhanchao** [comment]
找到問題了，已經解決，更新到 1.1.20 可以解決。

**Comment by SydianAndrewChen** [comment]
问题已解决，感谢及时回复，star已给！
