### ISSUE TITLE
md文件名包含中文时上传不了图片

### ISSUE THREAD

**Issue by zunpan** [imlinhanchao/vsc-markdown-image#64]
![image](https://user-images.githubusercontent.com/45265770/167250668-9d727b64-ff60-4c8f-8342-6802aabd6408.png)

我用的是github图床，全英文文件名能正常粘贴图片

**Comment by imlinhanchao** [comment]
請問你 file name format 的配置是什麽樣？

**Comment by zunpan** [comment]
> 請問你 file name format 的配置是什麽樣？

![image](https://user-images.githubusercontent.com/45265770/167335535-8da27068-8d4c-446a-a174-78799e3fb087.png)

**Comment by zunpan** [comment]
> 问题已修正，更新到1.1.21可解

你好，可能还存在一些问题。
![image](https://user-images.githubusercontent.com/45265770/167393962-4a8bcfda-260d-4f9e-8d73-5164f081213b.png)
上图中图1是挂掉的。

访问图片链接的结果是
![image](https://user-images.githubusercontent.com/45265770/167394093-272da01a-8332-40ed-aa07-ba4c14be72cf.png)

仓库中的图片位置是
![image](https://user-images.githubusercontent.com/45265770/167394211-ae42c5ab-509e-46b8-aace-2e18e16cfebe.png)

我把file name format 里面的${mdname}去掉后，插入图片的路径是上图的图2

**Comment by imlinhanchao** [comment]
已修正，更新到 1.1.22 版本可解。
