### ISSUE TITLE
针对 github 的加速链接建议增加一个 raw.fastgit.org 的选项

### ISSUE THREAD

**Issue by dotnetDoge** [imlinhanchao/vsc-markdown-image#66]
针对 github 的加速链接建议增加一个 raw.fastgit.org 的选项，比如下面连个链接

目前内置的加速链接用的是 jsdelivr 的：

https://cdn.jsdelivr.net/gh/dotnetDoge/picbed@main/markdown/1652795809527_manual_settings.png

建议增加一个选项，fastgit：

https://raw.fastgit.org/dotnetDoge/picbed/main/markdown/1652795809527_manual_settings.png

原因如下：

- 更快：经过我和其他几个小伙伴的验证，fastgit 的加速链接地址普遍比 jsdelivr 快（我不清楚其它地区的网络环境是怎么样的）
- 更稳：在 github 账户名或者仓库名有变动的情况下，虽然把相关引用链接地址都更新了，jsdelivr 的链接貌似不论怎么改都无效，而 fastgit 的加速链接不会有这个问题

感谢 @imlinhanchao 给大家提供了一个这么好用的插件

**Comment by abctel** [comment]
如果能够自定义其实更好吧，现在很多提供这种镜像服务的。

**Comment by imlinhanchao** [comment]
@abctel @dotnetDoge 扩展已经支援 GitHub CDN 自定义，可更新到 1.2.23 设置。
