### ISSUE TITLE
windows7 无法使用

### ISSUE THREAD

**Issue by clq9920** [imlinhanchao/vsc-markdown-image#67]
如题，粘贴图片后，会显示正在上传，但是失败，不会产生文件，也不会在vscode中产生文字

不知道要提供什么样的信息。

**Comment by clq9920** [comment]
![image](https://user-images.githubusercontent.com/48880318/169686328-b103cf28-2b4d-4428-9528-ef2cd927d79f.png)
![image](https://user-images.githubusercontent.com/48880318/169686353-15df53bd-6089-424e-8c36-414d0647a4b5.png)

只改了这两个参数

**Comment by imlinhanchao** [comment]
确认一下有没有安装PowerShell

**Comment by clq9920** [comment]
> 确认一下有没有安装PowerShell

刚刚更新了最新版的powershell就可以了，原来的1.0版powershell不支持。
