### ISSUE TITLE
一些小功能

### ISSUE THREAD

**Issue by clq9920** [imlinhanchao/vsc-markdown-image#68]
是否可以添加“图 x”文字的自定义功能，如删除或者改成英文等
```
![图 5](images/2022-05-21-21-39-40.png) 
```
自定义“图 5”文本

还有能否为本地图片的删除，移动提供一些自动化的操作，如删除图片，可以把源文件一起删除，移动图片，可以把源图片放入剪切板，之后就可以在新文件中快速粘贴

**Comment by imlinhanchao** [comment]
此功能已支援
