### ISSUE TITLE
图片保存到本地的时候似乎不用变量定义路径？

### ISSUE THREAD

**Issue by SydianAndrewChen** [imlinhanchao/vsc-markdown-image#69]
![image](https://user-images.githubusercontent.com/65159293/172084156-face54f3-48b9-410b-a6df-59251061dd22.png)
如果按照如图定义图片保存路径，似乎保存的时候不会正常解析
![image](https://user-images.githubusercontent.com/65159293/172084200-6ebb1be2-7df0-49d7-b914-cae7bf14a8b6.png)

我看这里似乎是有Notice说You can't use variable in here. 但是后面又说You can use variable。想问一下这里究竟能不能用呢？

**Comment by imlinhanchao** [comment]
是能用，但是要在後面鏈接那個設置選項上使用。

**Comment by hyramchn** [comment]
![image](https://user-images.githubusercontent.com/20043335/175440530-af76e3eb-971d-4652-a538-1f333d703d20.png)
在这里用。然后就可以了，我开始也以为不行。插件很棒

**Comment by SydianAndrewChen** [comment]
好的，看起来是我使用方面有问题，我先close掉，自己看一下
