### ISSUE TITLE
[Suggestion] Support for .mdx files

### ISSUE THREAD

**Issue by thomaskoppelaar** [imlinhanchao/vsc-markdown-image#7]
Hello,

I love this extension! I'd also love to have this extension work with [MDX](https://github.com/mdx-js/mdx)) files. Having looked at this only very briefly, it seems that it would be possible to do with only a minor change needed. 

Within package.json: 
![image](https://user-images.githubusercontent.com/36331365/88063227-15be8200-cb6a-11ea-8742-2ccf0e7f91e6.png)

I'd love to hear your feedback.

**Comment by imlinhanchao** [comment]
OK, I will update tomorrow.

**Comment by thomaskoppelaar** [comment]
I can submit a PR as well, is that ok?

**Comment by imlinhanchao** [comment]
Yes, it’s ok. There is just a little problem. The code in the repository is not up to date. I updated the extension this morning. But I forgot to push the code up. Please wait until I come to the company tomorrow to push up the morning update and then merge your PR. 😅

**Comment by thomaskoppelaar** [comment]
That's fine! Thanks for the quick reply :smile:

**Comment by imlinhanchao** [comment]
The update was published. You can update to version 1.0.8 .
