### ISSUE TITLE
通过scp上传图片到指定远程工作区

### ISSUE THREAD

**Issue by abctel** [imlinhanchao/vsc-markdown-image#70]
我看到之前有网友提到通过ssh远程写作的时候，无法粘贴图片，作者的答复是无法调用远程的某些API，今天看到一个paste image ftp插件想到，能不能增加通过scp或者sftp的方式先将图片保存到本地目录，再上传到指定规则的远程路径这样的功能来实现。

**Comment by imlinhanchao** [comment]
感谢你的建议，现在扩展已经支援远程模式，可参考注意事项设置：
https://github.com/imlinhanchao/vsc-markdown-image/blob/1.1.28/README.zh-cn.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
