### ISSUE TITLE
linux下保存到本地，相对路径问题

### ISSUE THREAD

**Issue by JouSF-1409** [imlinhanchao/vsc-markdown-image#73]
图片一般保存在本地，使用相对路径保存。用坚果云实现跨平台。后来发现找不到图片，仔细一查发现
![image](https://user-images.githubusercontent.com/81711503/179803657-a71dac18-9288-4440-9bd5-c03ec632026b.png)
`\home`开始是我linux端笔记的位置。很明显，调用的时候变成了相对位置/“绝对位置”。

**Comment by imlinhanchao** [comment]
你的设置是什么？

**Comment by JouSF-1409** [comment]
linux端：
upload method: local
local Path: /home/jousk/Documents/nutstore/notes/_resources/
默认打开的笔记工作区在notes这一层。

应该是最开始的 / 被读成相对路径了

**Comment by imlinhanchao** [comment]
不是很理解，local Path `/` 開始的話，會是使用VSCode打開的目錄開始計算路徑。你的路徑要是如何才能被正確找到呢？

**Comment by JouSF-1409** [comment]
>local Path `/` 開始的話，會是使用VSCode打開的目錄開始計算路徑。

linux端所有的路径都是从`/`开始的。这下相对路径与绝对路径就不好区分了。
我是后来才想起来设置里有说明`/`开始表示打开目录的。

之后的改进中，如果要使用相对路径的话，local path里规定一个字符开头？
