### ISSUE TITLE
希望可以增加一个修改图片引用名称格式的设置

### ISSUE THREAD

**Issue by Binhacker1024** [imlinhanchao/vsc-markdown-image#76]
关闭md文档后，再次打开后，图片引用[ ]会重置
* 对于markdown，可以修改[\]中的格式
`![picture ${prompt}](images/img.png)`
* 对于HTML，可以修改alt="\"中的内容
`<img alt="image ${prompt}" src="image/img.png">`

**Comment by Re-dorn** [comment]
同求，好像到现在都没支持这个

**Comment by imlinhanchao** [comment]
我找时间搞一下吧~如果有人可以提 PR 是最好的。😀 最近工作超级忙

**Comment by num-e** [comment]
@imlinhanchao 👍

**Comment by imlinhanchao** [comment]
@Binhacker1024 @Re-dorn @Andy-Dihong-Luo @num-e 1.1.34 已支援。

**Comment by num-e** [comment]
@imlinhanchao  哇！太效率了，必须赞一个 👍 

如果可以自定义个整个文本就更好啦。比如，我可能会自定义成：

```html
<figure><a href="${placeholder1}"><img src="${imgurl}" alt="${filename}"></a><figcaption>${placeholder2}</figcaption></figure>
```

这样就可以直接插入一个带图片标题的 html 代码段了 😄

**Comment by imlinhanchao** [comment]
你这个想法挺不错，等我下次抽空搞一下。

> @imlinhanchao 哇！太效率了，必须赞一个 👍
> 
> 如果可以自定义个整个文本，而不只是 alt 的内容，就更好啦。比如，我可能会自定义成：
> 
> ```
> <figure><a href="${placeholder1}"><img src="${imgurl}" alt="${filename}"></a><figcaption>${placeholder2}</figcaption></figure>
> ```
> 
> 这样就可以直接插入一个带链接、标题描述的图片了 😄
