### ISSUE TITLE
2022年8月vscode更新1.71后无法上传图片

### ISSUE THREAD

**Issue by GeekXtop** [imlinhanchao/vsc-markdown-image#78]
实测2022年8月vscode更新1.71后无法上传图片。
回退1.70.2后正常
插件没有看到打印日志
所以报错不知道是哪里
vscode插件开发我还不会
辛苦作者大大看一下了

**Comment by imlinhanchao** [comment]
好的。我看看

**Comment by GeekXtop** [comment]
> 我刚刚测试了 1.71.0 没有问题，你是使用哪种上传方式？

我使用的Github方式，图片png格式，直接复制到剪切板的。
就是左下角状态显示 激活扩展 上传图片 ，然后没有任何反应了。

**Comment by imlinhanchao** [comment]
试试用local可以复制到目录吗？

**Comment by GeekXtop** [comment]
> 试试用local可以复制到目录吗？

我尝试重启Windows，清空剪切板条目，再更新1.71可以使用了😂
不知道是否跟云剪切板有关？可能我之前复制了图片，实际上读取到了别的文字条目所以并没有激活扩展
可能是Windows奇奇怪怪的bug

不好意思打扰您了，感谢您做出这么优秀的插件

另外有一个小问题，我之前使用的coding做图床，但是coding政策变更，现在不登录看不到图片了。未来版本中您可以考虑删除coding支持
![image](https://user-images.githubusercontent.com/103322869/188475092-c69d9eb5-f72c-4970-ae5f-b007eef47409.png)

**Comment by imlinhanchao** [comment]
噢噢，好的。确实有可能有影响。插件是通过系统脚本读取的剪贴板，可能会被别的软件干扰。
