### ISSUE TITLE
`Get 0 images` when pasting image on Windows with Remote SSH

### ISSUE THREAD

**Issue by joaociocca** [imlinhanchao/vsc-markdown-image#80]
The idea of your extension seemed perfect for the only functionality I feel is lacking on VS Code!

But when I try to paste a capture image (either with Alt+Shift+V or right-click > Paste Image), nothing happened.

I thought I'd then look on the VSCode Dev Tools and there it was: `[Extension Host] Get 0 images workbench.desktop.main.js:87`

![image](https://user-images.githubusercontent.com/6473725/201454261-463c8911-101e-4b5e-87ba-6053b9abd763.png)

When inspecting line 87, it shows the ondulated underline of an error:

![image](https://user-images.githubusercontent.com/6473725/201454342-57f47ff1-7197-4abd-b865-ed8af3304d24.png)

Prettifying the code, the error seems to be on line 29860 of the workbench.desktop.main.js:

![image](https://user-images.githubusercontent.com/6473725/201454549-afc6e332-d29a-4e3f-816e-ee0a0dce9519.png)

I'm not much of a programmer, but it seems the extension is using a `Buffer()` deprecated function? I tried to find this `Buffer()`, seems like there's only 2 occurences: line 51931 and line 246735

![image](https://user-images.githubusercontent.com/6473725/201454671-fc46b5d1-b014-499c-8e9a-e0b29a9433cd.png)

![image](https://user-images.githubusercontent.com/6473725/201454679-5697b16b-de4f-4ff5-8db0-78720bba9894.png)

I'm running `VS Code 1.73.1` on `Windows 11 Pro 22H2 22621.819`, but remoting into a Kali (based off Ubuntu, `Linux kali 5.19.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1kali2 (2022-10-10) x86_64 GNU/Linux`) session (which has `xclip 0.13` installed).

Could this be related to the error I get when trying to run xclip in this session? I always get a `Error: Can't open display: (null)` message.

Any ideas on how to make it work?

**Comment by imlinhanchao** [comment]
Capture a image，and then execute this script https://github.com/imlinhanchao/vsc-markdown-image/blob/master/asserts/linux.sh like:
```bash
./linux.sh output.png 
```
Give me the output of command line，thks.

**Comment by joaociocca** [comment]
whoa, that was lightning fast. Hang on, gotta restore the VM.

Ok, grabbed the script, print in clipboard...

![image](https://user-images.githubusercontent.com/6473725/201456744-5f183db0-68fb-4866-9fa2-c9786e474881.png)

And, as expected, `Error: Can't open display: (null)`

**Comment by imlinhanchao** [comment]
I noticed you are using in a remote VM.  Unfortunately, xclip requires an X desktop, so it won't work in a remote VM.

**Comment by joaociocca** [comment]
I followed some instructions from https://stackoverflow.com/questions/65468655/vs-code-remote-x11-cant-get-display-while-connecting-to-remote-server and got remote tmux to succesfully transfer content to my local clipboard

![image](https://user-images.githubusercontent.com/6473725/201457544-3980fc1c-f142-406c-abf6-581fc84b8817.png)

But when executing the `linux.sh` script you pointed to, all I get is a new error:

![image](https://user-images.githubusercontent.com/6473725/201457566-05ec8e96-18ec-4bd2-9435-bf623c3011aa.png)

then I tried again and...

![image](https://user-images.githubusercontent.com/6473725/201457574-2d839164-80f9-4618-a6b8-84140287a36b.png)

But it was only the text I had previously copied... 

![image](https://user-images.githubusercontent.com/6473725/201457616-9c3f4707-ec07-43b1-902b-2e034446d332.png)

let's try again with the above image in the clipboard...

Yeah, no deal.

![image](https://user-images.githubusercontent.com/6473725/201457645-8ddce36e-a324-4ede-bb4a-839f0c9c8bb6.png)

It's grabbing an even older content I copied from tmux (you can see it on the first print here)

**Comment by joaociocca** [comment]
New error: "Could not load markdown it plugin". I tried searching for this, but couldn't find it. I found two "markdown-it-*" related, but not simply "markdown-it".
![image](https://user-images.githubusercontent.com/6473725/201458291-3af38efa-5886-477a-9b1c-155a137c29fc.png)

The buffer warning seems to be a VS Code known issue, attempted to be fixed [here](https://github.com/microsoft/vscode/issues/136874), but still ongoing [here](https://github.com/microsoft/vscode/issues/82524).

**Comment by joaociocca** [comment]
HA! Found out that the functionality is on experimental and already working actually! <3
https://github.com/microsoft/vscode/issues/164843#issuecomment-1294460344

But thanks for developing this and for attempting to help me =) Keep being awesome!
