### ISSUE TITLE
Save image folder in the current subfolder

### ISSUE THREAD

**Issue by brianjoubert** [imlinhanchao/vsc-markdown-image#81]
Hello,

It would be very convenient for me if the image folder were created in the same folder of the markdown file. Then each folder with notes would have its own image folder.

**Comment by imlinhanchao** [comment]
you can use the var `${mdname}`

**Comment by imlinhanchao** [comment]
No, you should set it in `markdown-image.base.fileNameFormat`

**Comment by imlinhanchao** [comment]
You can see this https://github.com/imlinhanchao/vsc-markdown-image/issues/32

**Comment by brianjoubert** [comment]
Thanks a lot. The only way I made it work was by adding a folder before like this. It's not perfect but it is already something :)

![image](https://user-images.githubusercontent.com/1177784/202237952-bcc06ca6-e5f4-47b7-9657-f6233da755dc.png)

**Comment by imlinhanchao** [comment]
Maybe you can show a folder tree what you want to make. I can told you how to setting.

**Comment by brianjoubert** [comment]
Thanks a lot

Now I have this

![image](https://user-images.githubusercontent.com/1177784/202387340-ac507d1d-7922-487b-8f68-5d471bfd403a.png)

But I would like that:

![image](https://user-images.githubusercontent.com/1177784/202387477-401d9d10-3886-4478-a631-2f2923987247.png)


If in markdown-image Local path I enter only : /images it creates the folder outside of the subfolder.

Once I changed it to pictures/images it creates it in the subfolder I am in (which is what I want) but I don't need to have these two folders. I would like one folder named images created in the current subfolder

Thanks a lot for your help

**Comment by imlinhanchao** [comment]
you can set to `./images`
