### ISSUE TITLE
插件使用：无法复制粘贴图片问题

### ISSUE THREAD

**Issue by Taootrum** [imlinhanchao/vsc-markdown-image#83]
你好，linhaochao：
目前使用该插件，出现图片无法复制粘贴问题。
一直显示uploading
![image](https://user-images.githubusercontent.com/37130412/204257044-b922f453-8c91-40c7-8624-b49bc1608b36.png)

我的环境： windows + vscode + ubuntu20.04

请帮忙看下是什么原因，谢谢！！！

**Comment by Taootrum** [comment]
从#43 看到，是当前工具不支持远程服务器模式吗？

**Comment by imlinhanchao** [comment]
是的，不支持

**Comment by Taootrum** [comment]
好的谢谢

**Comment by imlinhanchao** [comment]
现在扩展已经支援远程模式，可参考注意事项设置：
https://github.com/imlinhanchao/vsc-markdown-image/blob/master/README.zh-cn.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
