### ISSUE TITLE
Paste上去时github cdn自动使用jsdelivr url存在路径问题

### ISSUE THREAD

**Issue by williamium3000** [imlinhanchao/vsc-markdown-image#84]
hello！paste的时候使用github作为cdn，自动会用jsdelivr进行加速，但是jsdelivr的路径没有考虑到branch，导致无法加载图片。请问如何能修改jsdelivr的路径呢？
for e.g.
我在github上mynote repo下的images branch存放了一张图a.png
paste时候自动输出的url是
`![图 11](https://cdn.jsdelivr.net/gh/williamium3000/mynote/2345.png) `
但实际上由于我放在branch images中，应该为
`![图 11](https://cdn.jsdelivr.net/gh/williamium3000/mynote@images/2345.png) `
请问这个这么处理呢。源码似乎也没有找到有关cdn.jsdelivr.net的东西。上传图片没有问题 可以自动上传。

**Comment by imlinhanchao** [comment]
这是个 bug，我会修正。

**Comment by imlinhanchao** [comment]
已修正，更新到 1.2.23 可解决。

**Comment by williamium3000** [comment]
好的 感谢

**Comment by chenxizhang** [comment]
@imlinhanchao  我也遇到同样的问题，错误消息是 Failed to fetch version info for chenxizhang/pics.

https://cdn.jsdelivr.net/gh/chenxizhang/pics@master/3750cc1eda66ac8a072f667b7696c9a25a134b5855a2a8a2550f273c4913c2f5.png

**Comment by imlinhanchao** [comment]
> @imlinhanchao 我也遇到同样的问题，错误消息是 Failed to fetch version info for chenxizhang/pics.
> 
> https://cdn.jsdelivr.net/gh/chenxizhang/pics@master/3750cc1eda66ac8a072f667b7696c9a25a134b5855a2a8a2550f273c4913c2f5.png

使用这种方式，你的仓库得是公开的。

**Comment by chenxizhang** [comment]
@imlinhanchao 谢谢啊，这么快就回复了。我刚才设置为public了，但好像还是不行，是不是要等会儿？还是有什么设置么

**Comment by imlinhanchao** [comment]
可能是被cdn缓存了，可以试试改个项目名

**Comment by chenxizhang** [comment]
@imlinhanchao 已经能工作了，你太厉害了，感谢啊
