### ISSUE TITLE
图片路径不对

### ISSUE THREAD

**Issue by zunpan** [imlinhanchao/vsc-markdown-image#85]
之前图片路径：
```
![图 3](https://cdn.jsdelivr.net/gh/zunpan/note-imgur/2022.06~2022.11%E5%AE%9E%E4%B9%A0%E6%80%BB%E7%BB%93/IMG_20221203-201430967.png)  
```
现在的图片路径：
```
![图 3](https://cdn.jsdelivr.net/gh/zunpan/note-imgur%40main/2022.06~2022.11%E5%AE%9E%E4%B9%A0%E6%80%BB%E7%BB%93/IMG_20221208-203856741.png)  
```

图片可以在浏览器打开，github图床也有，就是vscode显示不了
Markdown Image版本：1.1.24
 
配置没有修改过
![image](https://user-images.githubusercontent.com/45265770/206451670-ae1c5865-673c-45c9-9b48-f3834b6d3da3.png)
![image](https://user-images.githubusercontent.com/45265770/206451727-fbf93b7c-edf9-4af7-adc1-f3caa58d3b17.png)
![image](https://user-images.githubusercontent.com/45265770/206451828-6f261c75-0c22-4d8b-9f1d-e6620a11e3eb.png)
![image](https://user-images.githubusercontent.com/45265770/206451867-eb740055-8a0f-4a19-93d1-f5907ce5ffaf.png)

**Comment by imlinhanchao** [comment]
看起来是@转码问题，这有点奇怪，上次测试是正常的，我明天调试看看。

**Comment by imlinhanchao** [comment]
已修正，更新到 1.1.25 可解决。
