### ISSUE TITLE
Support for Backblaze B2 & Amazon S3

### ISSUE THREAD

**Issue by mayankguptadotcom** [imlinhanchao/vsc-markdown-image#88]
Love the plugin, thank you so much for building it.
I was just wondering, are you planning to add support for Backblaze B2 or Amazon S3 in upcoming releases?

Thanks much!

**Comment by imlinhanchao** [comment]
I have never used b2 and s3. If you know how to write node. You can give me a PR. You just need to implement a upload function and package the setting options. Here is a sample. https://github.com/imlinhanchao/vsc-markdown-image/pull/56

**Comment by imlinhanchao** [comment]
@mayankguptadotcom Hi~ The extension was already supported s3. Can you test it and feedback the result to me?
