### ISSUE TITLE
SM.MS 一直上传文件失败 read ECONNRESET

### ISSUE THREAD

**Issue by soyaine** [imlinhanchao/vsc-markdown-image#90]
Mac 
VSCode 1.75.0
Markdown Image v1.1.26

使用 option+shift+V 粘贴，报错：
![image](https://user-images.githubusercontent.com/12845017/216556590-487c6a80-a707-4c17-bea2-474905c1ed0a.png)

设置如下：
![image](https://user-images.githubusercontent.com/12845017/216557656-4df8e03c-0434-4741-9d15-acf732c6398f.png)
![image](https://user-images.githubusercontent.com/12845017/216557786-9f303b7c-bdd7-41ff-9126-c38133ade0c2.png)

**Comment by JouSF-1409** [comment]
我在archlinux下也一样，我的设置：
![image](https://user-images.githubusercontent.com/81711503/217215544-09a9f8ff-8316-4cfb-b712-e87349ede02c.png)
![image](https://user-images.githubusercontent.com/81711503/217215686-2ec8846c-ecca-4ad2-9c1a-4fb0a6c59514.png)

**Comment by imlinhanchao** [comment]
这个错误是网络链接不上。
