### ISSUE TITLE
deepin系统上传一直提示上传

### ISSUE THREAD

**Issue by resolvejs** [imlinhanchao/vsc-markdown-image#91]
系统是deepin社区版本，通过vscode本地上传，已经安装了插件，一直显示上传中，也没有报错

![image](https://user-images.githubusercontent.com/46347187/217694185-eff0dea7-3f22-4c51-bffa-81fadeebdd8e.png)

**Comment by imlinhanchao** [comment]
看看 `输出` 里的 `扩展` 有没有什么输出？

**Comment by JouSF-1409** [comment]
> 

我遇到了类似的问题，archlinux，也是保存到本地。windows端没有问题，但linux端一直上传。`输出`里这么显示
````
[info] ExtensionService#_doActivateExtension hancel.markdown-image, startup: false, activationEvent: 'onCommand:markdown-image.paste'
````

**Comment by imlinhanchao** [comment]
看看命令行是否可以执行 xclip

**Comment by JouSF-1409** [comment]
> 看看命令行是否可以执行 xclip

我参照[这篇文章](https://blog.csdn.net/jhsword/article/details/108946287)测试了一下，xclip应该是正常的。
![image](https://user-images.githubusercontent.com/81711503/218320869-929e7368-d878-43cd-bcfc-fcbc9617a70b.png)

**Comment by LinuserLi** [comment]
ubuntu 22.04  -live-desktop TLS 版本 也出现同样的问题。上传配置的是本地，但是一直转圈圈 正在上传...

**Comment by imlinhanchao** [comment]
我找时间再搭个系统测试一下吧，之前测试的系统已经被我格了。

**Comment by ekkoful** [comment]
![image](https://user-images.githubusercontent.com/42363586/223328608-f9cb1319-ec40-4f11-b04a-463d5772275f.png)
os: ubuntu20.04
vscdoe:
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:25:16.105Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.15.0-60-generic
Sandboxed: No

**Comment by gmyzloed75349** [comment]
Me too!

**Comment by imlinhanchao** [comment]
1.1.29 版本已修正
