### ISSUE TITLE
deepin v20.8粘贴图片问题，已安装xclip,粘贴一直显示上传，但是只设置了本地保存

### ISSUE THREAD

**Issue by gmyzloed75349** [imlinhanchao/vsc-markdown-image#92]
![image](https://user-images.githubusercontent.com/117251925/223612583-db5e7521-0634-4860-ae7a-e5730aa48424.png)
![image](https://user-images.githubusercontent.com/117251925/223612644-7f2a05e8-c846-4964-93fd-6b8a9dc7e4df.png)
如题：deepinv20.8 该插件无法保存图片文件到本地

**Comment by KuiWei004** [comment]
我也是这个问题

**Comment by imlinhanchao** [comment]
1.1.29 版本已修正
