### ISSUE TITLE
插件很棒，请问有计划增加一下远程开发下图片粘贴的支持吗？

### ISSUE THREAD

**Issue by liqiwen0729** [imlinhanchao/vsc-markdown-image#93]
插件很棒，请问有计划增加一下远程开发下图片粘贴的支持吗？

vscode经常是通过remote-ssh连接到服务器上进行开发，在远程状态下本地clipboard图片粘贴无效。请问作者后续会增加这个功能吗？

**Comment by imlinhanchao** [comment]
远程开发要支援恐怕很难，因为本插件的功能是基于本地系统脚本去实现的，要做到 remote-ssh 上使用，就需要要两个不同的系统之间传输图片数据，目前看起来似乎是无法实现的。

**Comment by imlinhanchao** [comment]
vscode读取clipboard的API仅支援文本

**Comment by imlinhanchao** [comment]
现在扩展已经支援远程模式，可参考注意事项设置：
https://github.com/imlinhanchao/vsc-markdown-image/blob/master/README.zh-cn.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
