### ISSUE TITLE
在相对路径的情况下，如果对编辑的文档进行移动文件目录，比如移动到下级目录，那么图片的路径就会失效

### ISSUE THREAD

**Issue by fweiger** [imlinhanchao/vsc-markdown-image#96]
在相对路径的情况下，如果对编辑的文档进行移动文件目录，比如移动到下级目录，那么图片的路径就会失效

比如默认是在 A 文件夹下，创建文件 1.md,在 1.MD 粘贴图片后。如果在 A 文件夹下创建一个 A1 的文件，把 1.MD 移动到 A1 文件夹，那么图片的显示就失效了。

我知道主要也是 1.md的图片路径还是在 A 的找，是否有在移动文件夹的时候自动更新 1.md 的文件路径呢？或者其他的解决方案？使用绝对路径？

**Comment by imlinhanchao** [comment]
这个不是本扩展可以解决的问题，建议可以采用相对路径的方式，将图片跟随markdown文件保存，比如把 `markdown-image.local.path` 设置为 `./images`
