### ISSUE TITLE
是否可以添加一个上传png还是jpg的选项？

### ISSUE THREAD

**Issue by xhuaustc** [imlinhanchao/vsc-markdown-image#99]
现在所有上传的图片都是png的，文件比原文件大。如果能够将它使用jpeg压缩下，会节约线上流量，加快加载速度。同时也能满足绝大部分的需求了。

**Comment by xhuaustc** [comment]
确实如此。我的一般操作是在网上查找到需要的图片后，使用浏览器的右击->复制图片。这种会把网页上的jpg文件变成了png文件，同时大小也变大了。
现在可以先把文件下载下来，再复制文件的方式，可以解决这个问题。

**Comment by imlinhanchao** [comment]
1.1.31 版本已支援
